### ISSUE TITLE
link was broken of readme

### ISSUE THREAD

**Issue by tfzxyinhao** [cloudwego/netpoll#1]
hi, the link of [KiteX](https://github.com/cloudwego/kitex) is 404

**Comment by Hchenn** [comment]
Sorry, due to internal review, open source such as KiteX may be delayed for 1-2 weeks. Thanks for your attention.

**Comment by YangruiEmma** [comment]
> hi, the link of [KiteX](https://github.com/cloudwego/kitex) is 404

[Kitex](https://github.com/cloudwego/kitex) has been public! Thank you for your attention.

**Comment by YangruiEmma** [comment]
This issue has been resolved.
