### ISSUE TITLE
hertz 啥时候开源

### ISSUE THREAD

**Issue by lizhaode** [cloudwego/netpoll#100]
想试用一下

**Comment by Duslia** [comment]
大概明年3月份开源，现在还在做一些完善工作，希望给用户一个更好的使用体验~

**Comment by lazychanger** [comment]
可以加入内测嘛？
@Duslia

**Comment by Duslia** [comment]
现在还没有内测计划哈，如果想内测的话可以找我内推加入字节~

**Comment by lazychanger** [comment]
😂难。
基础不行。

**Comment by NWUFLAME** [comment]
已经三月了哦，怎么样

**Comment by Duslia** [comment]
在打磨的时候发现还有一点问题，开源大概 delay 到6月份了🥺

**Comment by hiqsociety** [comment]
can open source now? we see the issue as we help fix?

**Comment by hiqsociety** [comment]
can open source now? we see the issue as we help fix?

**Comment by hiqsociety** [comment]
does it support quic / http3?

**Comment by Duslia** [comment]
> is the api same as fasthttp?

The API is a little different from fasthttp since we optimize it.

**Comment by Duslia** [comment]
> does it support quic / http3?

Hertz doesn't support quic/http3. However, it provides a convenient protocol extension interface and you can extend it by yourself.  Also, you are welcome to contribute your code to the community.

**Comment by hiqsociety** [comment]
does it support http2?

**Comment by Duslia** [comment]
Of course. But we don't think it has reached a state where it can be open source. So We will open source in a later stage. If you have a strong need, welcome to submit issue to try it out.

**Comment by hiqsociety** [comment]
i would love to try it out. how to try it out?

**Comment by Duslia** [comment]
Thank you for your great support! Hertz will open source soon, and you can submit an issue to try out HTTP2.

**Comment by xinfanghaolaopao** [comment]
hertz估计何时开源，期待好久了！

**Comment by Duslia** [comment]
> hertz估计何时开源，期待好久了！

@xinfanghaolaopao  大概月底之前~

**Comment by xinfanghaolaopao** [comment]
👍+100

**Comment by xinfanghaolaopao** [comment]
顺便了解下：字节的Service Mesh是自研的还是istio等二开的，有开源的意向吗，谢谢！

**Comment by ruokeqx** [comment]
已经开源了 源码都看完了 可以Close issue了
