### ISSUE TITLE
graceful shutdown failed

### ISSUE THREAD

**Issue by lazychanger** [cloudwego/netpoll#107]
EventLoop 的 OnRequest 内，链接被主动关闭时，会导致链接（processing）死锁，从而无法关闭。

OnRequest
```golang
func (s *server) onHandle(_ context.Context, conn netpoll.Connection) error {
	time.Sleep(time.Second * 3)
	conn.Close()
	return nil
}
```

connection_onevent.go:115
![image](https://user-images.githubusercontent.com/20916944/150730103-38f4000c-7a3a-4e7b-901a-9ccb3286f28c.png)
![image](https://user-images.githubusercontent.com/20916944/150730204-e3626723-6095-4366-8f3a-62fc858cf672.png)

**Comment by Hchenn** [comment]
确实，pr #102 对此问题进行了修复，并在下个版本发布

**Comment by lazychanger** [comment]
我在PR #102 中还没有看到此修复。
`c.unlock(processing)`这段代码是没有副作用的，我觉得直接提到 `if !c.IsActive()` 之前更好，因为此时链接是非活跃状态又或者handler已经处理完了，理应该立即解锁。

**Comment by Hchenn** [comment]
不知道咱们说的是不是一回事儿，`processing` 关闭阶段 = 1 是 by design 的；有问题的是 graceful shutdown 对 `isIdle()` 的判断，修复在 `netpoll_server.go:62-89`

**Comment by lazychanger** [comment]
我仔细看了哈，你并没有修复该问题。`isIdle`函数中的`c.isUnlock(processing)`会导致`isIdle`永远返回`false`。永远返回`false`的原因在我issue的截图描述可以看到哈。

connection_onevent.go:166
```golang
func (c *connection) isIdle() (yes bool) {
	return c.isUnlock(processing) &&
		c.inputBuffer.IsEmpty() &&
		c.outputBuffer.IsEmpty()
}
```

**Comment by Hchenn** [comment]
亲，你咋不信呢。原先的问题是把 `s.connections` 用数组额外缓存了，而连接关闭时会有 `CloseCallback` 把自己从 `s.connections` 里清除掉。

**Comment by lazychanger** [comment]
嗯嗯，没住到下面的AddCloseCallback的delete
