### ISSUE TITLE
Need Optimization in CPU Intensive Scenarios

### ISSUE THREAD

**Issue by hnes** [cloudwego/netpoll#109]
**Is your feature request related to a problem? Please describe.**

In CPU intensive scenarios, Netpoll performs a little worse than go native net:

CPU usage of RPC servers:

![cpu-usage-of-rpc-server](https://user-images.githubusercontent.com/7548307/152098105-0205f6f5-b93e-4de1-bc34-f1c098f9675e.png)

NetPoll:

![NetPoll](https://user-images.githubusercontent.com/7548307/152098107-184ea4b7-3174-45b8-a315-2f81a6b65ed5.png)

Go Native Net:

![Go Net](https://user-images.githubusercontent.com/7548307/152098110-70f1206d-01b5-4d26-b960-3812f5101fd1.png)

[netpoll-benchmark sources used to benchmark](https://github.com/hnes/netpoll-benchmark/tree/a19f98f563f667715db97bac2df155352081b7f2)

[The commit to cpu-intensive-fy the benchmark](https://github.com/hnes/netpoll-benchmark/commit/a19f98f563f667715db97bac2df155352081b7f2)

**Describe the solution you'd like**

Maybe we need some optimizations for NetPoll when it is running in CPU-intensive scenarios?

**Describe alternatives you've considered**

No idea.

**Comment by joway** [comment]
@hnes 
When you are using concurrent `1000` that means there are too many goroutines exist and everyone occupied P(processor) long time. That makes netpoll's poller cannot take the P timely.

But in real-time services, most of the time, it will not fill all CPUs(tanks to autoscaling or others) so the situation will not be so bad.

If you still want to use Netpoll in this scenario, you may adjust the poller event loop number.

**Comment by hnes** [comment]
@joway Thanks a lot.
