### ISSUE TITLE
operatorCache 中的cache有什么特殊意义吗

### ISSUE THREAD

**Issue by Ccheers** [cloudwego/netpoll#117]

**Comment by Ccheers** [comment]
`
var opcache *operatorCache

type operatorCache struct {
	locked int32
	first  *FDOperator
	cache  []*FDOperator // 此处只有写引用 并没有读引用
}

func (c *operatorCache) alloc() *FDOperator {
	c.lock()
	if c.first == nil {
		const opSize = unsafe.Sizeof(FDOperator{})
		n := block4k / opSize
		if n == 0 {
			n = 1
		}
		// Must be in non-GC memory because can be referenced
		// only from epoll/kqueue internals.
		for i := uintptr(0); i < n; i++ {
			pd := &FDOperator{}
			c.cache = append(c.cache, pd)
			pd.next = c.first
			c.first = pd
		}
	}
	op := c.first
	c.first = op.next
	c.unlock()
	return op
}
`

**Comment by Hchenn** [comment]
unsafe pointer 可以提升代码效率，但同时影响了 runtime 引用计数，因此需要使用 persistent memory 来防止 GC 混乱。关于这点，可以直接参考官方实现 https://github.com/golang/go/blob/master/src/runtime/netpoll.go#L613

**Comment by Hchenn** [comment]
> > unsafe pointer 可以提升代码效率，但同时影响了 runtime 引用计数，因此需要使用 persistent memory 来防止 GC 混乱。关于这点，可以直接参考官方实现 https://github.com/golang/go/blob/master/src/runtime/netpoll.go#L613
> 
> 明白了 另外 #52 的问题 为什么 loop 变量要 全局申明才能 避免 GC 有相关的文章说明吗

可能是这个库本身骚操作太多，#52 已经修复了，现在还有问题吗 ？

**Comment by Ccheers** [comment]
> > > unsafe pointer 可以提升代码效率，但同时影响了 runtime 引用计数，因此需要使用 persistent memory 来防止 GC 混乱。关于这点，可以直接参考官方实现 https://github.com/golang/go/blob/master/src/runtime/netpoll.go#L613
> > 
> > 
> > 明白了 另外 #52 的问题 为什么 loop 变量要 全局申明才能 避免 GC 有相关的文章说明吗
> 
> 可能是这个库本身骚操作太多，#52 已经修复了，现在还有问题吗 ？

没有问题，只是好奇为啥会被GC😂
