### ISSUE TITLE
性能、内存占用问题

### ISSUE THREAD

**Issue by lesismal** [cloudwego/netpoll#12]
用于压测的echo server代码在这里： [server](https://github.com/lesismal/go_network_benchmark/blob/master/netpoll/netpoll.go)

压测客户端100个连接、payload 64，代码在这：[client](https://github.com/lesismal/go_network_benchmark/blob/master/client.go)

跟其他几个库相比，都是append一个新的buffer用于写，其他框架也可以直接写读到的buffer、但也都用了append的新buffer回写，所以这应该不影响各个框架性能对比

不知道现在这个echo server代码正确了没，用这个代码测，100连接、1k payload，吞吐量只有 gnet 的一半左右，甚至比 easygo还慢一些。。

如果方便，请提供下你们的benchmark代码我重新跑下看看

**Comment by lesismal** [comment]
其他网络库使用相同的环境、 相同的client压测，情况正常

**Comment by lesismal** [comment]
直接这样用读到的buffer回写，吞吐量可能比easygo强一点，比gnet还是低很多
```golang
reader := connection.Reader()
buf, err := reader.Next(reader.Len())
if err != nil {
        return err
}
n, err := connection.Write(buf)
```

**Comment by Hchenn** [comment]
压测代码会在后续更新，有兴趣可以加入用户群一起讨论 https://github.com/cloudwego/kitex#%E8%81%94%E7%B3%BB%E6%88%91%E4%BB%AC
