### ISSUE TITLE
waitRead 为什么 waitReadSize 设定成 N？

### ISSUE THREAD

**Issue by Ccheers** [cloudwego/netpoll#121]
```go 
// waitRead will wait full n bytes.
func (c *connection) waitRead(n int) (err error) {
	if n <= c.inputBuffer.Len() {
		return nil
	}
	atomic.StoreInt32(&c.waitReadSize, int32(n)) // 这里为什么不设置成 int32(n-c.inputBuffer.Len())
	defer atomic.StoreInt32(&c.waitReadSize, 0)
	if c.readTimeout > 0 {
		return c.waitReadWithTimeout(n)
	}
	// wait full n
	for c.inputBuffer.Len() < n {
		if c.IsActive() {
			<-c.readTrigger
			continue
		}
		// confirm that fd is still valid.
		if atomic.LoadUint32(&c.netFD.closed) == 0 {
			return c.fill(n)
		}
		return Exception(ErrConnClosed, "wait read")
	}
	return nil
}

// inputAck implements FDOperator.
func (c *connection) inputAck(n int) (err error) {
	if n < 0 {
		n = 0
	}
	// Auto size bookSize.
	if n == c.bookSize && c.bookSize < mallocMax {
		c.bookSize <<= 1
	}

	length, _ := c.inputBuffer.bookAck(n)
	if c.maxSize < length {
		c.maxSize = length
	}
	if c.maxSize > mallocMax {
		c.maxSize = mallocMax
	}

	var needTrigger = true
	if length == n { // first start onRequest
		needTrigger = c.onRequest()
	}
	if needTrigger && length >= int(atomic.LoadInt32(&c.waitReadSize)) {
		c.triggerRead()
	}
	return nil
}
```
`
atomic.StoreInt32(&c.waitReadSize, int32(n)) // 这里为什么不设置成 int32(n-c.inputBuffer.Len())
`
如果need的是一个大包或者实际只有几B读延迟，不就阻塞了吗

**Comment by Hchenn** [comment]
因为 `int32(n-c.inputBuffer.Len())` 多一次 `atomic.Load` 明显要不直接 store `int32(n)` 慢；以及这里没有什么逻辑 bug, 后面说的阻塞是指 ？

**Comment by Ccheers** [comment]
> 因为 `int32(n-c.inputBuffer.Len())` 多一次 `atomic.Load` 明显要比直接 store `int32(n)` 慢；以及这里没有什么逻辑 bug, 后面说的阻塞是指 ？

哦哦，是我看错了，`length, _ := c.inputBuffer.bookAck(n)`这里会重新计算一次未读取的包大小，阻塞是担心如果需要预读取8字节数据，实际只传输过来2字节，需要等待后续数据送达，这样一个routine就陷入了阻塞

**Comment by Hchenn** [comment]
> > 因为 `int32(n-c.inputBuffer.Len())` 多一次 `atomic.Load` 明显要比直接 store `int32(n)` 慢；以及这里没有什么逻辑 bug, 后面说的阻塞是指 ？
> 
> 哦哦，是我看错了，`length, _ := c.inputBuffer.bookAck(n)`这里会重新计算一次未读取的包大小，阻塞是担心如果需要预读取8字节数据，实际只传输过来2字节，需要等待后续数据送达，这样一个routine就陷入了阻塞

对，read 是 block 的，这里对齐 `bytes`/`bufio` 等库的行为，减少上层代码改动。

**Comment by Ccheers** [comment]
> > > 因为 `int32(n-c.inputBuffer.Len())` 多一次 `atomic.Load` 明显要比直接 store `int32(n)` 慢；以及这里没有什么逻辑 bug, 后面说的阻塞是指 ？
> > 
> > 
> > 哦哦，是我看错了，`length, _ := c.inputBuffer.bookAck(n)`这里会重新计算一次未读取的包大小，阻塞是担心如果需要预读取8字节数据，实际只传输过来2字节，需要等待后续数据送达，这样一个routine就陷入了阻塞
> 
> 对，read 是 block 的，这里对齐 `bytes`/`bufio` 等库的行为，减少上层代码改动。

好的，谢谢~
