### ISSUE TITLE
Nil Pointer Dereference Panic

### ISSUE THREAD

**Issue by minogump** [cloudwego/netpoll#127]
**Describe the bug**
Nil pointer dereference panic

**Stack trace**
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x107e94a]

goroutine 6 [running]:
github.com/cloudwego/netpoll.(*linkBufferNode).Len(...)
	/opt/test/pkg/mod/github.com/cloudwego/netpoll@v0.2.1/nocopy_linkbuffer.go:721
github.com/cloudwego/netpoll.(*LinkBuffer).GetBytes(...)
	/opt/test/pkg/mod/github.com/cloudwego/netpoll@v0.2.1/nocopy_linkbuffer.go:559
github.com/cloudwego/netpoll.(*connection).outputs(0xc02bbfc000, 0xc000288000, 0x20, 0x20, 0xc02bbfc000, 0x31242, 0x0, 0x0)
	/opt/test/pkg/mod/github.com/cloudwego/netpoll@v0.2.1/connection_reactor.go:110 +0x6a
github.com/cloudwego/netpoll.(*defaultPoll).handler(0xc0001d4e80, 0xc000280000, 0x1, 0x80, 0xc000280000)
	/opt/test/pkg/mod/github.com/cloudwego/netpoll@v0.2.1/poll_default_linux.go:165 +0x21a
github.com/cloudwego/netpoll.(*defaultPoll).Wait(0xc0001d4e80, 0x0, 0x1)
	/opt/test/pkg/mod/github.com/cloudwego/netpoll@v0.2.1/poll_default_linux.go:102 +0x139
created by github.com/cloudwego/netpoll.(*manager).Run
	/opt/test/pkg/mod/github.com/cloudwego/netpoll@v0.2.1/poll_manager.go:100 +0x52

**Desktop (please complete the following information):**
 - Version v0.2.1

**Comment by Hchenn** [comment]
Are you using `kitex` or just `netpoll` ? 

`outputs` indicates that a large data packet is currently being sent, is there any operation on `LinkBuffer` during this period?
