### ISSUE TITLE
block read?

### ISSUE THREAD

**Issue by lesismal** [cloudwego/netpoll#13]
看了下 connection 的实现，如果 Next(n) 时对方没有发出足够 n 的数据，这个读将被阻塞，如果有大量慢连接 m 个，这意味着需要使用 m 个协程、否则其他 connection 将被线头阻塞

https://github.com/cloudwego/netpoll/blob/main/connection_impl.go#L327

如果每个连接一个协程，那可能不如直接用标准库了

**Comment by Hchenn** [comment]
读阻塞不会影响其他 connection，你可能对代码有误解。

**Comment by lesismal** [comment]
> 读阻塞不会影响其他 connection，你可能对代码有误解。

我的意思是说，读阻塞会占用这个协程，如果肯为这种慢连接消耗一个协程，那就相当于退化成标准库了。
而异步库要解决的主要问题是海量并发时协程数量巨大而带来的内存和调度成本开销
