### ISSUE TITLE
open source the v0.1 of hertz so we can try out and help improve?

### ISSUE THREAD

**Issue by hiqsociety** [cloudwego/netpoll#137]
open source the v0.1 of hertz so we can try out and help improve?

u can do v0.2 when ready as a framework.

just want to ready the api to connect and use hertz. currently using fasthttp. looking at conversion

**Comment by YangruiEmma** [comment]
hertz will open source in May or June ;)

**Comment by hiqsociety** [comment]
hope to see http2 automatic letsencrypt certbot working with it.
thx!
