### ISSUE TITLE
nil pointer panic

### ISSUE THREAD

**Issue by guijianshi** [cloudwego/netpoll#149]
`
goroutine 11 [running]:
github.com/cloudwego/netpoll.(*LinkBuffer).book(0xc00a115450, 0x10000, 0x1cb75, 0xbbc, 0x0, 0x0)
        pkg/mod/github.com/cloudwego/netpoll@v0.2.3/nocopy_linkbuffer.go:581 +0xb5
github.com/cloudwego/netpoll.(*connection).inputs(...)
        pkg/mod/github.com/cloudwego/netpoll@v0.2.3/connection_reactor.go:72
github.com/cloudwego/netpoll.(*defaultPoll).handler(0xc00028fae0, 0xc000308000, 0x2, 0x80, 0xc000308000)
        pkg/mod/github.com/cloudwego/netpoll@v0.2.3/poll_default_linux.go:137 +0x556
github.com/cloudwego/netpoll.(*defaultPoll).Wait(0xc00028fae0, 0x0, 0x1)
        pkg/mod/github.com/cloudwego/netpoll@v0.2.3/poll_default_linux.go:103 +0x14e
created by github.com/cloudwego/netpoll.(*manager).Run
        pkg/mod/github.com/cloudwego/netpoll@v0.2.3/poll_manager.go:103 +0x52
`

**Comment by Hchenn** [comment]
fixed but not released yet. (#142)
you can rely on the develop branch for the time being.
