### ISSUE TITLE
[GLCC 赛题] 使用 io_uring 实现 netpoll I/O 轮询器

### ISSUE THREAD

**Issue by cloudwegoIce** [cloudwego/netpoll#151]
**🚩GLCC 高校编程夏令营赛题**
👏欢迎大家参与～
> GLCC 是由中国计算机学会举办的高校开源编程夏令营活动，活动为项目准备了开源奖学金。请在以下链接中报名参与⬇️
>报名链接：[https://www.gitlink.org.cn/glcc/subjects/detail/98]( https://www.gitlink.org.cn/glcc/subjects/detail/98)
>关于issue相关问题、解题思路的答疑将在群内进行
<img width="197" alt="image" src="https://user-images.githubusercontent.com/104130938/170914107-081c4538-6e89-4f04-9720-bf5ba9e473be.png">

题目简介包含：
1、题目描述
Netpoll 是字节自研的 Golang RPC 网络库，默认使用 epoll 作为 I/O 轮询器，同时支持扩展实现。
io_uring 则是近年来提出的高效异步 I/O 内核接口，我们希望使用 io_uring 实现（不同于 epoll 的）netpoll I/O 轮询器，提供更优秀的性能。

2、编码任务
- 整理 io_uring Golang 版本 SDK
- 设计并实现几种可能的轮询器
- 性能测试和方案优化 

3、技能要求和编程语言
Golang

4、预期完成结果
实现高性能的 io_uring I/O 轮询器

**Comment by Jacob953** [comment]
Hi, @Hchenn! Plz assign this to me. ;)

**Comment by GuangmingLuo** [comment]
Project Closure
