### ISSUE TITLE
thread per core golang like glommio / seastar?

### ISSUE THREAD

**Issue by hiqsociety** [cloudwego/netpoll#156]
thread per core golang like glommio / seastar?

**Comment by Hchenn** [comment]
no thread-per-core here, we only configure the number of goroutines listening for epoll, through the SetNumLoops API

**Comment by hiqsociety** [comment]
do u think there's a possibility to use thread per core in future + io_uring for this? i mean is it part of the roadmap?
like monoio

**Comment by Hchenn** [comment]
E.. monoio is coded in rust, golang I think might be hard to implement it, custom goruntime doesn't seem to be accepted.
So maybe the solution `rust -> cgo -> golang` is better?

**Comment by hiqsociety** [comment]
what's the overhead like with cgo calling golang? i heard it's extremely terrible. right?

**Comment by Hchenn** [comment]
> 

not yet researched ...

**Comment by joway** [comment]
golang cannot let user side codes to imlement the thread-per-core architecture. and cgo is not a good idea to be used in high performance use-case. @hiqsociety
