### ISSUE TITLE
can this do prefork and have prefork benchmark?

### ISSUE THREAD

**Issue by hiqsociety** [cloudwego/netpoll#157]
can this do prefork and have prefork benchmark?

**Comment by Hchenn** [comment]
Do you mean multi-process prefork ? 
No, we don't have process or thread level control, all operations are based on goroutine.

**Comment by hiqsociety** [comment]
is this faster or slower than using goroutine in general? in terms of req/s u reckon?
coz according to techempower benchmark, prefork mode is faster
https://www.techempower.com/benchmarks/#section=data-r20&hw=ph&test=plaintext

**Comment by Hchenn** [comment]
I understand this benchmark and have seen some top-ranked repos, but I don't think it can be used as a reference for production environments.

I've seen some prefork repos before, but haven't gotten the inspiration yet. I still need to learn more in the future.

In short, prefork is planned for future research
