### ISSUE TITLE
Broken link for multisyscall

### ISSUE THREAD

**Issue by jim3ma** [cloudwego/netpoll#16]
The link in README is not available https://github.com/cloudwego/multisyscall.

**Comment by Hchenn** [comment]
Not open source yet, thanks for your attention.

**Comment by jim3ma** [comment]
Emm, how to optimize multiple syscall ?

**Comment by 1Jo1** [comment]
@jim3ma  io_uring allows your to batch syscalls in one syscall :)

**Comment by Hchenn** [comment]
io_uring is indeed a better solution, we will support it later.

**Comment by 1Jo1** [comment]
@Hchenn thats cool, is that open source as well?

**Comment by Hchenn** [comment]
Yes, but it may have to wait a few months
