### ISSUE TITLE
Is ReadBinary still a faster implementation of Next+copy under single node scenario?

### ISSUE THREAD

**Issue by WineChord** [cloudwego/netpoll#163]
![image](https://user-images.githubusercontent.com/20353612/172856777-93fbf9c0-3051-4435-862f-ff658df28642.png)

![image](https://user-images.githubusercontent.com/20353612/172856949-6aba1a55-c386-42ad-8dfb-5843b23666b6.png)

![image](https://user-images.githubusercontent.com/20353612/172857170-4cb45325-e948-4f23-9508-f2fbed428936.png)

It is easy to see that under multiple nodes scenario, `Next` involves another additional cache making or slice making. I wonder if `ReadBinary` is still a faster implementation of `Next`+`copy` under single node scenario, where `ReadBinary` looks just like `Next`+`copy`.

**Comment by Hchenn** [comment]
sorry, I don't quite understand this question, can you describe it more ?

As shown in Figure 1, the behavior of `ReadBinary` is exactly `Next + copy`.

The `return args of ReadBinary` does not depend on the `buffer` itself, but the `Next returned` cannot be used after calling `Release`, which is their main difference.

**Comment by WineChord** [comment]
Thank you for your quick reply. I am fluttered. I know the semantic of `Next`. The point I am curious about is the claim:

```golang
	// ReadBinary is a faster implementation of Next when it needs to
	// return a copy of the slice that is not shared with the underlying layer.
	// It replaces:
	//
	//  var p, err = Next(n)
	//  var b = make([]byte, n)
	//  copy(b, p)
	//  return b, err
	//
```

I am curious about the performance between 

```golang
var p, err = Next(n)
var b = make([]byte, n)
copy(b, p)
return b, err
```

and 

```golang
ReadBinary(n)
```

As I can see from the code, when `n` crosses multiple nodes, you need to call `malloc`(L98) or `make([]byte, n)`(L101) which introduce additional overhead(so `Next`+`copy` is inferior than `ReadBinary`). But if `n` is enough to read from single node, then the behavior of `ReadBinary` is exactly the same with `Next`+`copy`(which means equal performance). I am here just checking if I have missed some other points.

Besides I think maybe `c.ReadBinary` can embed a call of `c.Release` in the end. Therefore users can simply write `c.ReadBinary` without manually calling `c.Release`.

**Comment by Hchenn** [comment]
I might get your point,  you are right about comparing `Next+copy` and `ReadBinary`.

But `Release` should not be involved here, `read buffer` is a continuous process, `Release` means `read done`. 
The whole behavior is like: `Next(read), ReadBinary(read), ... Release(done)`, preferably `Release` is called only once.

**Comment by WineChord** [comment]
Now I have a clearer understanding of the code. Thx!
