### ISSUE TITLE
gopool中最大goroutine数问题

### ISSUE THREAD

**Issue by yangqingxin1993** [cloudwego/netpoll#172]
默认的gopool池最大容量为10000，当活跃连接数超过10000时，新建连接会由于没有goroutine而得不到处理？

**Comment by Hchenn** [comment]
会排队，通过 `gopool.SetCap` 可以自行调整最大值

**Comment by yangqingxin1993** [comment]
如果是长连接场景，超过goroutine阈值时，当前的活跃连接如果没有关闭，新连接就会一直出于队列中，直到存量连接关闭后，才会腾出goroutine去处理？这样会导致新建连接可能存在较大的处理延时？

**Comment by Hchenn** [comment]
> 如果是长连接场景，超过goroutine阈值时，当前的活跃连接如果没有关闭，新连接就会一直出于队列中，直到存量连接关闭后，才会腾出goroutine去处理？这样会导致新建连接可能存在较大的处理延时？

你是遇到实际问题了吗，不如具体描述一下？
netpoll 维护的 活跃连接数 和 goroutine 数不是 1:1 的关系，这点在 README 里已经说明了，理论上不存在这类问题。

**Comment by yangqingxin1993** [comment]
> netpoll 维护的 活跃连接数 和 goroutine 数不是 1:1 的关系

使用[hertz-examples/hello](https://github.com/cloudwego/hertz-examples/tree/main/hello)做了下1000个长连接的压测，查看pprof中goroutine数是1000左右，在不超过gopool阈值的场景下，活跃连接数与goroutine数基本是1:1的关系。

压测命令：wrk -c 1000 -t 32 -d 10m --latency http://10.199.189.26:8888/hello

**Comment by yangqingxin1993** [comment]
修改了下gopool中默认阈值10000->1000， 然后使用2000个长连接压测，此时另外启动一个命令行窗口，curl请求会一直出于等待响应状态

**Comment by Duslia** [comment]
Hertz 可以配置 idletimeout 管理连接，但这个功能需要上层持有连接，也就导致了连接和协程1：1。 如果不需要这个功能的话，可以把 idletimeout 设置成0
