### ISSUE TITLE
关于benchmark代码、更多参数和测试指标

### ISSUE THREAD

**Issue by lesismal** [cloudwego/netpoll#18]
目前benchmark代码的链接已经失效，希望能早点提供测试用例完整代码

目前文档中benchmark的图，只包括了 100连接（没提到 payload）以及 payload 1k（没提到连接数）的指标，测试内容太少、能够说明的情况也局限

希望能提供不同并发情况下，比如1k、10k、100k、1000k场景下不同payload时与其他网络库、标准库的指标对比

另外由于本人参考文档写的echo server压测时发现netpoll内存占用非常高，而内存占用也是海量并发场景时的重要指标。所以希望也能提供包括内存占用以及其他指标的数据对比

**Comment by YangruiEmma** [comment]
我们的同学正在整理哈，近期会发出来的，看到你前面的issue了，可以等测试代码库public出来哈，稍等一下下哦~ 
没有特殊说明的话，通常都是1K，不明确的地方我们再补充下

**Comment by lesismal** [comment]
好的。

**Comment by cch123** [comment]
希望能够提供 8c 以上的数据

**Comment by lesismal** [comment]
> 希望能够提供 8c 以上的数据

活捉golang妖怪一只，:kissing_heart:

**Comment by lesismal** [comment]
> 希望能够提供 8c 以上的数据

投诉，头像太拉垮，能不能换个漂亮或者帅气的

**Comment by joway** [comment]
hi, https://github.com/cloudwego/kitex-benchmark 已经 public
