### ISSUE TITLE
Bind User Session With Conn

### ISSUE THREAD

**Issue by da-tai** [cloudwego/netpoll#181]
A way to create and use sessions.

Similar to https://github.com/lesismal/nbio#bind-user-session-with-conn

```
var conn netpoll.Connection = ...
var session *YourSessionType = ... 
conn.SetSession(session)
```

```
var conn netpoll.Connection = ...
session := conn.Session().(*YourSessionType)
```

**Comment by joway** [comment]
session is a business/protocol level concept. In raw tcp, only have a binary stream. Can you describe that what session you want?

**Comment by da-tai** [comment]
I was thinking of business logic here so that I set variables based on the tcp messages sent. Re reading the doc, I may either use a map to store all sessions based on the netpoll.Connection or store it in context.
