### ISSUE TITLE
构建的websocket server, 在处理operation code, 写入返回帧数据异常

### ISSUE THREAD

**Issue by gh73962** [cloudwego/netpoll#188]
**Describe the bug**
server 收到opcode=9 的ping帧,server返回opcode=10的pong帧
opcode https://tools.ietf.org/html/rfc6455#section-5.2
但在实际运行时收不到pong帧
基于对比github.com/mailru/easygo/netpoll 可以收到响应头

**To Reproduce**
```go
// server
import (
    "github.com/gobwas/ws"
    "github.com/gobwas/ws/wsutil"
)
func connect(ctx context.Context, conn netpoll.Connection) context.Context {
	_, err := ws.Upgrade(conn)
	if err != nil {
		conn.Close()
		return ctx
	}
	return ctx
}

func handle(ctx context.Context, conn netpoll.Connection) error {
    header, err := ws.ReadHeader(w.conn)
    if err != nil {
         return err
    }

    if header.OpCode.IsControl() {
        // 此处根据控制码返回相应的帧
        if err := wsutil.ControlFrameHandler(conn, ws.StateServerSide)(header, conn); err != nil {

	}
        return
    }
    // read
    // write
}
```

```go
// client
        d := wsutil.DebugDialer{
		Dialer: ws.Dialer{
			Timeout: 1 * time.Second,
		},
	}
        conn, _, _, err := d.Dial(ctx, url)

	p := ws.NewPingFrame(nil)
	p.Header.Masked = true
	if err := ws.WriteFrame(conn, p); err != nil {
		log.Printf("WriteFrame failed,err=%+v", i, err)
	}

	h, err := ws.ReadFrame(conn)
	log.Printf("header=%+v, err=%+v", h, err)
```

**Expected behavior**
客户端期待收到 header={Header:{Fin:true Rsv:0 OpCode:10 Masked:false Mask:[0 0 0 0] Length:0} Payload:[]}
实际是未收到

go version 1.18
server os : 本地 WSL UBUNTU 22.04 和 测试环境k8s alpine 3.16

**Additional context**
参考方案 https://www.freecodecamp.org/news/million-websockets-and-go-cc58418460bb
参考example https://github.com/gobwas/ws-examples/tree/master/src/chat

**Comment by Hchenn** [comment]
我看了下，你这边的测试应该是发 10 次，最后一次回包丢了是吧 ？

**Comment by gh73962** [comment]
wsutil.ControlFrameHandler在执行HandlePing写入数据后conn就失效不可用, 并且对端没有收到数据
除此以外收发数据都是正常的,24h小时持久性测试和压测都通过了

**Comment by gh73962** [comment]
![image](https://user-images.githubusercontent.com/31007143/183031550-5bfb5c0a-caa9-44f9-ae51-01f9625c2a71.png)

**Comment by gh73962** [comment]
个人代码问题,非netpoll导致

**Comment by leeson1995** [comment]
@gh73962  大佬啥问题啊～
