### ISSUE TITLE
长连接时可能是惊群问题

### ISSUE THREAD

**Issue by jacoblai** [cloudwego/netpoll#201]
**Describe the bug**
长连接时可能是惊群问题,当SetNumLoops大于1时，cpu占满，设置为1时一切正常。

**To Reproduce**
1. 编写一个最简单的长连接服务端，用map缓存所有conn客户端连接对象池。并设置SetNumLoops(4).
2. 编写一个最简单的tcp客户端，连接建立2000个连接。不断开。保持连接，60s一个心跳包。
3. 现在观察服务端cpu，会发现cpu占满。
4. 然后把服务器端的SetNumLoops(1)，再重新测试观察cpu占用已降低到正常。

**Screenshots**
服务端参数：
<img width="723" alt="image" src="https://user-images.githubusercontent.com/11623139/192671544-14631597-342a-4408-9bc9-5b6b9a72b2b4.png">
客户端建立2千个连接，并保活。
<img width="315" alt="image" src="https://user-images.githubusercontent.com/11623139/192672017-0925fce2-b558-4d88-80f4-984367776dca.png">
此时的服务器端cpu情况：
<img width="515" alt="image" src="https://user-images.githubusercontent.com/11623139/192671880-e2571c13-7d4b-4da4-8b52-f0b25fd7c323.png">

**Desktop (please complete the following information):**
 - OS: mac book pro
 - Version 
 
<img width="214" alt="image" src="https://user-images.githubusercontent.com/11623139/192672143-0822e458-a1c1-4ed5-8551-89987bf935c9.png">

**Comment by Hchenn** [comment]
不是惊群效应，netpoll 没有这种机制。

我觉得更可能是测试代码没有处理 OnRequest (netpoll 是 LT 模式)，能否展示下测试代码，或者在我们的用户群里咨询下 ？

**Comment by jacoblai** [comment]
谢谢，以下是服务器端相关的代码段：
入口：
```
package main

var eng *broker.Engine
var srv netpoll.EventLoop

func init() {
	_ = netpoll.SetNumLoops(1) //非1惊群效应
	_ = netpoll.SetLoadBalance(netpoll.RoundRobin)
	_ = netpoll.DisableGopool()
}

func main() {
	setLimit()
	var addr = flag.String("l", ":1883", "host port (default 1883)")
	flag.Parse()

	eng = broker.NewEngine()

	listener, err := netpoll.CreateListener("tcp", *addr)
	if err != nil {
		panic("create netpoll listener failed")
	}

	srv, err = netpoll.NewEventLoop(
		OnMessage,
		netpoll.WithOnPrepare(Prepare),
		netpoll.WithOnConnect(OnConnect),
		netpoll.WithReadTimeout(2*time.Second),
		netpoll.WithIdleTimeout(30*time.Minute),
	)
	if err != nil {
		panic(err)
	}
	go func() {
		if err = srv.Serve(listener); err != nil {
			log.Println(err)
		}
	}()
}

func Prepare(conn netpoll.Connection) context.Context {
	return context.Background()
}

func OnConnect(ctx context.Context, conn netpoll.Connection) context.Context {
	_ = conn.AddCloseCallback(OnDisconnect)
	eng.AddClient(conn)
	return ctx
}

func OnDisconnect(conn netpoll.Connection) error {
	eng.DelClient(conn)
	return nil
}

func OnMessage(ctx context.Context, conn netpoll.Connection) (err error) {
	c, ok := eng.GetClient(conn)
	if ok {
		err = c.Receive() //这个是协议解包函数。它的逻辑是解决一个包后最少会回一个对应的响应包。
	}
	return err
}
```
engine代码：
```
type Engine struct {
	Clients    *sync.Map
}

func NewEngine() *Engine {
	eng := Engine{
		Clients:    &sync.Map{},
	}
	return &eng
}

func (e *Engine) AddClient(conn netpoll.Connection) *Client {
	c := NewClient(conn, e)
	e.Clients.Store(conn, c)
	return c
}

func (e *Engine) GetClient(conn netpoll.Connection) (*Client, bool) {
	c, ok := e.Clients.Load(conn)
	if ok {
		return c.(*Client), ok
	}
	return nil, ok
}

func (e *Engine) DelClient(conn netpoll.Connection) {
	e.Clients.Delete(conn)
}
```

**Comment by jacoblai** [comment]
代码已开源于 https://github.com/Coolpy7/Coolpy7_Community 请告知相关解决办法。谢谢！

**Comment by joway** [comment]
@jacoblai hi，我需要如何运行你前面的示例呢？另外，我确认下，你的压测试在 Macos 本地运行的？

**Comment by joway** [comment]
如果是在 Macos 本地运行的，你是否有 Linux 环境，再在 Linux 上测试下是否有这个问题呢？

**Comment by jacoblai** [comment]
你好，从一开始服务端和测试客户端都是在ubuntu20.04下测试的，测试工具用的是:  ./mqtt-stresser-linux-amd64 -broker tcp://192.168.0.7:7006 -num-clients 100 -num-messages 1500 -rampup-delay 1s -rampup-size 10 -global-timeout 30s -timeout 10s -constant-payload 100

**Comment by joway** [comment]
@jacoblai 我用 `./mqtt-stresser -broker tcp://127.0.0.1:1883 -num-clients 2000 -num-messages 1500 -rampup-delay 1s -rampup-size 10 -global-timeout 30s -timeout 10s -constant-payload 100` 没法复现。

![image](https://user-images.githubusercontent.com/8353464/198961454-8236d860-c75f-4c3e-8b1c-0373a169a97b.png)

或者你能提供一个CPU 跑满时候的 pprof cpu profile 文件吗？

**Comment by jacoblai** [comment]
> @jacoblai 我用 `./mqtt-stresser -broker tcp://127.0.0.1:1883 -num-clients 2000 -num-messages 1500 -rampup-delay 1s -rampup-size 10 -global-timeout 30s -timeout 10s -constant-payload 100` 没法复现。
> 
> ![image](https://user-images.githubusercontent.com/8353464/198961454-8236d860-c75f-4c3e-8b1c-0373a169a97b.png)
> 
> 或者你能提供一个CPU 跑满时候的 pprof cpu profile 文件吗？

不好意思，测试代码位于：https://github.com/Coolpy7/coolpy7_benchmark/blob/master/test_bench_sub/cp7_bench_sub.go 请修改一下连接ip:port直接连接测试就会出现此问题的了。

**Comment by joway** [comment]
遇到了这个错误 。。。 @jacoblai 

```
go run test_bench_sub/cp7_bench_sub.go
2022/10/31 19:33:54 1 {my_ip}
2022/10/31 19:33:54 0
2022/10/31 19:33:54 100
2022/10/31 19:34:04 conn wait future timeout
2022/10/31 19:34:04 sub client not connected
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x622bba]

goroutine 1 [running]:
main.main()
	/data00/home/tiger/tmp/coolpy7_benchmark/test_bench_sub/cp7_bench_sub.go:65 +0x6ba
exit status 2

```

**Comment by jacoblai** [comment]
不停的newengine这个方法，有点不可思议。我只在启动的时候new了一次。请问我们否哪里法用对？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Joway ***@***.***&gt;
发送时间: 2022年10月31日 19:42
收件人: cloudwego/netpoll ***@***.***&gt;
抄送: Li Donghai ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [cloudwego/netpoll] 长连接时可能是惊群问题 (Issue #201)





 
打了下huoyant火焰图，都是你自己代码占的 CPU 。。。

**Comment by joway** [comment]
@jacoblai 这个图的意思是这部分逻辑是在哪个栈下的，不是说这个函数不停调用了。总之与netpoll没有关系，你可以检查下你们代码逻辑

**Comment by jacoblai** [comment]
好的，谢谢你





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Joway ***@***.***&gt;
发送时间: 2022年10月31日 19:47
收件人: cloudwego/netpoll ***@***.***&gt;
抄送: Li Donghai ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [cloudwego/netpoll] 长连接时可能是惊群问题 (Issue #201)
