### ISSUE TITLE
conn断连触发Writer().Malloc() 空指针panic

### ISSUE THREAD

**Issue by aloha-hub** [cloudwego/netpoll#207]
****
当connect.Write.Malloc()申请buffer时报错空指针
rawConn.Writer().Malloc(length)
****

**报错详情**
{"log":"\u0009/usr/local/go/src/runtime/panic.go:1038 +0x215\n","stream":"stderr","time":"2022-10-29T12:39:04.37957735Z"}
{"log":"github.com/cloudwego/netpoll.(*LinkBuffer).growth(0xc000ff16a8, 0x71b939)\n","stream":"stderr","time":"2022-10-29T12:39:04.379580007Z"}
{"log":"\u0009/home/jenkins/agent/workspace/UAP_etcd_docker_buiild_PR-128/source/vendor/github.com/cloudwego/netpoll/nocopy_linkbuffer.go:777 +0x2d\n","stream":"stderr","time":"2022-10-29T
12:39:04.379584409Z"}
{"log":"github.com/cloudwego/netpoll.(*LinkBuffer).Malloc(0xc023e10730, 0x1a)\n","stream":"stderr","time":"2022-10-29T12:39:04.379588488Z"}
{"log":"\u0009/home/jenkins/agent/workspace/UAP_etcd_docker_buiild_PR-128/source/vendor/github.com/cloudwego/netpoll/nocopy_linkbuffer.go:332 +0x30\n","stream":"stderr","time":"2022-10-29T
12:39:04.37959221Z"}
{"log":"github.com/cloudwego/netpoll.(*connection).Malloc(0xc0016ca480, 0x13110a5)\n","stream":"stderr","time":"2022-10-29T12:39:04.379595779Z"}
{"log":"\u0009/home/jenkins/agent/workspace/UAP_etcd_docker_buiild_PR-128/source/vendor/github.com/cloudwego/netpoll/connection_impl.go:193 +0x25\n","stream":"stderr","time":"2022-10-29T12
:39:04.379598414Z"}

**复现场景**
rawConn 为netpoll.Connection
connection长时间无响应后，代码逻辑中会主动调用conn.rawConn.Close()
另一个goroutine中的在一直loop发送请求
```
func (conn *clinetConn) loop(){ 
      for  { 
		select{ 
		case buffer, ok := <-conn.Buff 
			if !ok{ 
				break 
			} 
			if conn.rawConn ==nil || !conn.rawConn.IsActive() { 
				break 
			} 
			buffer, err  :=  conn.rawConn.Writer().Malloc(length) // nil pointer panic 
                         // encode buffer 
                        conn.rawConn.Writer().Flush() 
		} 
	} 
}
```

**期望现象**
1. 当主动调用rawConn.Close()后，应该不会走到rawConn.Writer().Malloc()的逻辑
2.  如果正好rawConn.IsActive()状态检查完成后再断连的，Writer().Malloc()也应该是报错而不是panic

**环境**
OS : linux
Go version : 1.16
gnet version : github.com/cloudwego/netpoll v0.2.4

**Comment by joway** [comment]
在这种情况下，应该在用户侧保证代码不会出现 Close 和 写入相关的操作并发出现的情况。比如检查 conn 是否正在 writing，若是，则等待 write 结束在关闭。
