### ISSUE TITLE
question: why not use `sync.Pool`

### ISSUE THREAD

**Issue by alpha-baby** [cloudwego/netpoll#210]
https://github.com/cloudwego/netpoll/blob/a879ff8753d9610669c0a86af1e3145542641457/fd_operator_cache.go#L32

为什么这里不使用 sync.Pool  ?

**Comment by joway** [comment]
因为要自己控制生命周期

**Comment by li-jin-gou** [comment]
为什么 标题不是 `why not  use sync.Pool?` 😳

**Comment by alpha-baby** [comment]
> 为什么标题不是 `why not use sync.Pool` ? 😁

哈哈，写错了

**Comment by alpha-baby** [comment]
> 因为要自己控制生命周期

目前看，这个就是个简单的全局变量，没看出来有啥其他的控制逻辑，

直接使用 sync.Pool 又简单，性能估计比目前这个更好

**Comment by alpha-baby** [comment]
当然，目前绝大多数都是长连接场景，用不用内存池无伤大雅

**Comment by joway** [comment]
@alpha-baby 我的意思是，这个变量在内存中的生命周期，需要由代码手动控制，类似 c 里的手动释放。否则 go 只要看不到引用，就会把他 gc 了，而事实上 netpoll 在 epoll 中还要用到这个 operator。这个和 sync pool 没关系，用 sync pool 也不能脱离 gc 控制。

**Comment by alpha-baby** [comment]
> @alpha-baby 我的意思是，这个变量在内存中的生命周期，需要由代码手动控制，类似 c 里的手动释放。否则 go 只要看不到引用，就会把他 gc 了，而事实上 netpoll 在 epoll 中还要用到这个 operator。这个和 sync pool 没关系，用 sync pool 也不能脱离 gc 控制。

哦哦，好的

**Comment by alpha-baby** [comment]
> @alpha-baby 我的意思是，这个变量在内存中的生命周期，需要由代码手动控制，类似 c 里的手动释放。否则 go 只要看不到引用，就会把他 gc 了，而事实上 netpoll 在 epoll 中还要用到这个 operator。这个和 sync pool 没关系，用 sync pool 也不能脱离 gc 控制。

按理说 FDOperator 对象的引用不会丢失，
