### ISSUE TITLE
func OnRequest: context get 0 value under high concurrency

### ISSUE THREAD

**Issue by wangyao2016** [cloudwego/netpoll#217]
**Describe the bug**
I set value to context in func OnConnect like: context.WithValue(ctx, "key", val). Within ten threads, I can get correct value from OnRequest's context,  but under high concurrency like 40 threads, the context return 0 value and can't get value which I set in OnConnect.

**To Reproduce**
test with sysbench,  --threads=40

**Expected behavior**
Get context values correct.

**Panic**
 logger.go:190: [Error] GOPOOL: panic in pool: gopool.DefaultPool: interface conversion: interface {} is nil, not *server.ClientConn: goroutine 1858 [running]

![image](https://user-images.githubusercontent.com/16890042/204430222-4e8387a8-2d7c-4034-ace2-ddec3f35b135.png)

**Comment by wangyao2016** [comment]
sysbench 40并发压测时，OnRequest 方法 无法从context中获取value， ctx没用任何value

**Comment by joway** [comment]
@wangyao2016 你能分享下你的代码吗？方便我这边复现
