### ISSUE TITLE
当客户端主动关闭链接时，服务端获取不到完整的数据

### ISSUE THREAD

**Issue by zyiuh** [cloudwego/netpoll#220]
**Describe the bug**
当客户端主动关闭链接时，服务端获取不到完整的数据。

**To Reproduce**
1. 客户端发送消息并主动关闭链接。
2. 统计服务端收到的消息长度。
3. 消息实际长度为27260。

**Expected behavior**

**Screenshots**
客户端代码
<img width="880" alt="image" src="https://user-images.githubusercontent.com/96063477/207503552-c5eb4800-e0a6-4236-b92c-a02cc170d283.png">
服务端部分代码
<img width="553" alt="image" src="https://user-images.githubusercontent.com/96063477/207502903-11922eba-cb92-4dd3-876c-b5e833d0eb3d.png">
统计结果
<img width="142" alt="image" src="https://user-images.githubusercontent.com/96063477/207502921-f293a249-1bda-4336-85c7-7c60c5366040.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 13.0.1

**Comment by joway** [comment]
@zyiuh 可以发下 tcp 抓包数据吗？看看是 client 没有彻底发送完毕还是 server 没有接收完毕。

另外，如果你有 Linux 环境的话，也可以在 Linux 下试试看能否复现。

**Comment by zyiuh** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/96063477/207515987-1445e8c1-f1ed-4a2b-8f60-44a6f0a234cf.png">
可以确认的是client端的数据已经发送完毕了，linux也可以复现。

**Comment by joway** [comment]
@zyiuh 我写了一个测试没法复现你的问题。你确定 server 执行完了吗？要不你贴下代码吧

```
func TestWriteAndClose(t *testing.T) {
	var network, address = "tcp", ":18888"
	var recv int32
	var total int32 = 1000 * 1000
	var loop = newTestEventLoop(network, address,
		func(ctx context.Context, connection Connection) error {
			buf, err := connection.Reader().Next(connection.Reader().Len())
			if errors.Is(err, ErrConnClosed) {
				return err
			}
			MustNil(t, err)
			atomic.AddInt32(&recv, int32(len(buf)))
			return nil
		},
	)

	var conn, err = DialConnection(network, address, time.Second)
	MustNil(t, err)
	size := total / 100
	sendMsg := make([]byte, size)
	for i := int32(0); i < total; i += size {
		_, err = conn.Write(sendMsg)
		MustNil(t, err)
	}
	err = conn.Close()
	MustNil(t, err)

	for atomic.LoadInt32(&recv) != total {
		runtime.Gosched()
	}

	err = loop.Shutdown(context.Background())
	MustNil(t, err)
}

```

**Comment by joway** [comment]
@zyiuh 找到问题了，Close 的时候，如果一次没能读完所有数据，就会先关闭了连接。

**Comment by zyiuh** [comment]
@joway 确实是这样的，我这边暂时换成了net原生包实现，我会关注这个问题的，辛苦了

**Comment by joway** [comment]
@zyiuh hi, 我提了个 PR 修复了，你可以 go get github.com/cloudwego/netpoll@fix/server-close-v2 再试试

https://github.com/cloudwego/netpoll/pull/226

**Comment by zyiuh** [comment]
@joway 好的，我这边验证没什么问题了，感谢。
