### ISSUE TITLE
WSL2 run go build report netpoll error

### ISSUE THREAD

**Issue by JerryBluesnow** [cloudwego/netpoll#227]
root@JERRY test $ go build
# github.com/cloudwego/netpoll
../../pkg/mod/github.com/cloudwego/netpoll@v0.3.1/sys_sendmsg_linux.go:41:11: cannot use uint64(iovLen) (value of type uint64) as type uint32 in struct literal
../../pkg/mod/github.com/cloudwego/netpoll@v0.3.1/sys_sendmsg_linux.go:47:40: undefined: syscall.SYS_SENDMSG
../../pkg/mod/github.com/cloudwego/netpoll@v0.3.1/sys_zerocopy_linux.go:33:9: cannot use sec (variable of type int64) as type int32 in struct literal
../../pkg/mod/github.com/cloudwego/netpoll@v0.3.1/sys_zerocopy_linux.go:34:9: cannot use usec (variable of type int64) as type int32 in struct literal
# github.com/henrylee2cn/ameda
../../pkg/mod/github.com/henrylee2cn/ameda@v1.4.10/int.go:13:9: cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in return statement (overflows)
../../pkg/mod/github.com/henrylee2cn/ameda@v1.4.10/uint.go:13:9: cannot use math.MaxUint64 (untyped int constant 18446744073709551615) as uint value in return statement (overflows)

any suggestions?

**Comment by joway** [comment]
@JerryBluesnow which os and golang version you use?

**Comment by joway** [comment]
long time no reply, close the issue
