### ISSUE TITLE
Why `SetFinalizer` is needed when `eventLoop` exit in `Serve` func

### ISSUE THREAD

**Issue by ganlvtech** [cloudwego/netpoll#232]
https://github.com/cloudwego/netpoll/blob/6a5a4f7cb79118e1152c469c1b0ac216049a28c2/netpoll.go#L60-L61

This is the only [SetFinalizer](https://pkg.go.dev/runtime#SetFinalizer) in netpoll. No finalizer is defined before. Is it necessary here?

**Comment by joway** [comment]
because go's gc issues. https://github.com/cloudwego/netpoll/issues/52

In fact, we just use `SetFinalizer` to make the evl object alive and not been GC. not clear it's finalizer.
