### ISSUE TITLE
netpoll源码疑问

### ISSUE THREAD

**Issue by xj524598** [cloudwego/netpoll#239]
<img width="1078" alt="image" src="https://user-images.githubusercontent.com/26913796/223001445-ea2147a7-0ff5-481b-933e-c1c5e3c83e32.png">

如图在connection_reactor.go文件的inputAck方法 有个代码逻辑：
	var needTrigger = true
	if length == n { // first start onRequest
		needTrigger = c.onRequest()
	}
	if needTrigger && length >= int(atomic.LoadInt64(&c.waitReadSize)) {
		c.triggerRead()
	}

其中  length == n是不是只会在该链接第一次触发IO时候才会调用，后续该链接有其他数据，或者该链接多次处理七层协议后，只会触发
c.triggerRead()？
如果按照上述逻辑，我们在onRequest处理完毕之后，必须调用con.waitRead方法，进行阻塞等待？

**Comment by joway** [comment]
@xj524598  不是连接第一次触发 IO，而是第一次有新数据到达。具体来说，以 HTTP 长连接为例，每当开始读新的 requerst ，都会触发一次 onRequest。

你用的时候不需要关心这个，你只要从 connection 按照你的需求去解析和读取内容就行了。

**Comment by joway** [comment]
此外，此 onRequest 非你传进来的 onRequest 。你点进去看代码，会发现是一个 for 循环。一直到没有新数据可处理才结束

**Comment by errocks** [comment]
应该是疑惑, 还会有什么情况n != length ?

**Comment by xj524598** [comment]
好的感谢，那对于grpc这种一个链接同时跑多个request，怎么去理解尼？

**Comment by xj524598** [comment]
> 此外，此 onRequest 非你传进来的 onRequest 。你点进去看代码，会发现是一个 for 循环。一直到没有新数据可处理才结束

嗯这个逻辑我注意到了

**Comment by xj524598** [comment]
> 此外，此 onRequest 非你传进来的 onRequest 。你点进去看代码，会发现是一个 for 循环。一直到没有新数据可处理才结束

好的感谢，那对于grpc这种一个链接同时跑多个request，怎么去理解尼？

**Comment by xj524598** [comment]
> 应该是疑惑, 还会有什么情况n != length ?

也可以这么说

**Comment by xj524598** [comment]
此外对于之前netpoll有个延迟调度的优化，具体看下这个文章：https://www.infoq.cn/article/spasfyqgaaid5rguinl4
我的疑惑如下面2张图：
<img width="764" alt="image" src="https://user-images.githubusercontent.com/26913796/223053686-b9e299f6-24b5-4a65-b09e-da279bc9ab94.png">

<img width="866" alt="image" src="https://user-images.githubusercontent.com/26913796/223054195-bb24092c-b350-4663-9ebb-d30854cd7347.png">

**Comment by errocks** [comment]
<img width="1430" alt="image" src="https://user-images.githubusercontent.com/18068311/223055923-b8005ae3-27df-4038-8b77-2cf2bf4332ea.png">
我看了下代码, 应该是在connection closed的时候, 才会调到inputAck, 希望处理掉inputbuffer剩余的数据, 类似finalize的功能
如果length = n 直接onRequest 回调
如果length > n, 就是还有数据可以读, trigger一下, 读完为止
如果length < n, 忽略, return nil 当做是不是原子的可出来数据

不知道我这么理解对不对了

**Comment by errocks** [comment]
> 此外对于之前netpoll有个延迟调度的优化，具体看下这个文章：https://www.infoq.cn/article/spasfyqgaaid5rguinl4 我的疑惑如下面2张图： <img alt="image" width="764" src="https://user-images.githubusercontent.com/26913796/223053686-b9e299f6-24b5-4a65-b09e-da279bc9ab94.png">
> 
> <img alt="image" width="866" src="https://user-images.githubusercontent.com/26913796/223054195-bb24092c-b350-4663-9ebb-d30854cd7347.png">

> 而在无事件触发的场景下，使用 msec=0 显然会造成无限轮询，空耗大量资源。

文章说的比较清晰了, 就是因为没事干的时候, 就不要等了,主动把自己挂起, 比继续for 循环要节省资源

**Comment by joway** [comment]
@xj524598 
> 那对于grpc这种一个链接同时跑多个request，怎么去理解尼？
一个连接的读取一定是顺序的，多个request只是你分了多个协程去处理，但是你读request本身还是顺序读取的。

epoll loop 里主动调度的目的是因为，go 对于 syscall.Syscall 的调用会有阻塞等待的副作用，所以高并发下，最好不要轻易使用。尝试主动让出执行权，让其他工作继续运行一下，然后等到重新轮到loop执行的时候，大概率（繁忙情况下）已经有事件可以继续处理了，这样就可以保持一直在 RawSyscall 的调用中。

**Comment by xj524598** [comment]
> l 的调用中。

感谢
