### ISSUE TITLE
是否有必要维护workerPool？

### ISSUE THREAD

**Issue by halodou** [cloudwego/netpoll#24]
如果只是为了实现协程数量限制，仅维护逻辑上的workerCnt，直接使用go func()闭包就好了吧？还可以减少一次workerPool:Get/Put的开销。

**Comment by YangruiEmma** [comment]
不是为了限制协程数量，是为了复用协程，4c测试相比直接go func() 性能更好一些。如果你的服务cores很多，用gopool可能会引入锁开销，这个在gopool有单独的优化

**Comment by dyxushuai** [comment]
补充一点: worker pool 有个大的优化点是避免 goroutine 的栈扩张

**Comment by Hchenn** [comment]
> 如果只是为了实现协程数量限制，仅维护逻辑上的workerCnt，直接使用go func()闭包就好了吧？还可以减少一次workerPool:Get/Put的开销。

我来回复一下：

**Comment by Hchenn** [comment]
> 如果只是为了实现协程数量限制，仅维护逻辑上的workerCnt，直接使用go func()闭包就好了吧？还可以减少一次workerPool:Get/Put的开销。

我来回复一下：
1. 使用 workerPool 主要目的是复用 goroutine，减少栈扩张。在开源之前，由于依赖 netpoll 实现的框架必然存在栈扩张，所以 workerPool 是个默认项。
3. 但开源场景下，确实可能存在没有栈扩张的场景，此时维护 workerPool 反而是负收益。因此应该支持关闭 workerPool 的开关。

TODO: 
1. 支持 DisableGopool() 来关闭 gopool

**Comment by Hchenn** [comment]
solved: https://github.com/cloudwego/netpoll/pull/28
