### ISSUE TITLE
[Fasthttp] panic: BUG: net.Listener returned (nil, nil)

### ISSUE THREAD

**Issue by joeky888** [cloudwego/netpoll#241]
**Describe the bug**
Trying to integrate netpoll with an existing fasthttp project.

**To Reproduce**

With fasthttp the following code got panic: BUG: net.Listener returned (nil, nil) on startup.

Minimal code to reproduce:

```go
package main

import (
	"fmt"
	"log"

	"github.com/cloudwego/netpoll"
	"github.com/valyala/fasthttp"
)

func fastHTTPHandler(ctx *fasthttp.RequestCtx) {
	fmt.Fprintf(ctx, "Hi there! RequestURI is %q", ctx.RequestURI())
}

func main() {
	server := &fasthttp.Server{
		Handler: fastHTTPHandler,
	}

	const addr = ":12567"

	ln, err := netpoll.CreateListener("tcp4", addr)
	if err != nil {
		log.Fatalf("Create listener failed: %s\n", err)
	}

	log.Printf("Listening on %s\n", addr)
	if err := server.Serve(ln); err != nil {
		log.Fatalf("Error in ListenAndServe: %s\n", err)
	}
}

```

**Expected behavior**
Should be ok for both net and netpool.

**Screenshots**

**Desktop (please complete the following information):**
Go 1.20 macOS/Linux. With latest commit
`github.com/cloudwego/netpoll v0.3.3-0.20230301065315-6704628e5d13`

**Comment by joway** [comment]
Hi, now netpoll cannot use like such way. As a server,  you should use NewEventLoop API to integrate your protocol layer. https://github.com/cloudwego/netpoll-examples/blob/main/server.go#L30

**Comment by joeky888** [comment]
Thanks! Is this a intended behavior or will be improved in the foreseeable future?

**Comment by joway** [comment]
@joeky888 netpoll is a trade-off between compatibility and performance. go net pefer compatibility and netpoll perfer performance. That's why it maybe cannot used simply by fasthttp or otherthing like that. But we now still commit oneself to improve the compatibility. 

So, for answer your question, yes, we will let netpoll more easy to use in the future.
