### ISSUE TITLE
Status of netpoll io_uring

### ISSUE THREAD

**Issue by kaber2** [cloudwego/netpoll#246]
Hello,

thank you for your work on this. I was considering working on this myself when I found your implementation.

What is the current status of your implementation in your judgement? Is it usable, do you need testers or someone to help you work on this?

**Comment by joway** [comment]
duplicate https://github.com/cloudwego/netpoll/issues/77

**Comment by joway** [comment]
@kaber2 We now have a interval version of uring, but it will have a lot of changes in netpoll. And, we dont know how it will affect stability because we dont have many uring use-cases in production environment. But if you want to implement it, welcome to provide your implement.

**Comment by kolinfluence** [comment]
@joway 
1. possible to open source the internal version of uring?
2. how much speed up compared with vanilla netpoll?

**Comment by joway** [comment]
@kolinfluence previous answer already explained it.
