### ISSUE TITLE
resource temporarily unavailable error

### ISSUE THREAD

**Issue by ym2049** [cloudwego/netpoll#253]
使用netpoll开发tcp server，在OnRequest里从连接去读取数据经常报resource temporarily unavailable错误，请问是啥原因？是我使用方式不对吗？（已经检查过系统资源类似cpu、mem、fd之类是没问题） 大致代码如下：
r := bufio.NewReaderSize(conn, 1024)
conn.SetReadDeadline(time.Now().Add(5*time.Second)
buf := make([]byte, 1024)
_, err = io.ReadFull(r, buf)
if err != nil {
    return err //resource temporarily unavailable
}

**Comment by joway** [comment]
Please show the full example of your usage.

**Comment by ym2049** [comment]
简化代码：
func OnRequest(ctx context.Context, conn netpoll.Connection) error {
        defer conn.Close

        r := bufio.NewReaderSize(ch, 1024)
        for {
                header := make([]byte, 4)
                conn.SetReadDeadline(time.Now().Add(5*time.Second)
                _, err := io.ReadFull(r, header)
        		if err != nil {
                	return err //resource temporarily unavailable
        		}

        		body := make([]byte, conv2Length(header))
        		conn.SetReadDeadline(time.Now().Add(5*time.Second)
        		_, err := io.ReadFull(r, body)
        		if err != nil {
                	return err  //resource temporarily unavailable
        		}

        		//handle body
        }
        return nil
}


func bootstrapServer() error {
        el, err := netpoll.NewEventLoop(OnRequest)
        if err != nil {
                return err
        }

        l, err := net.Listen(s.opt.Network, s.opt.Address)
        if err != nil {
                return err
        } 

        if err := el.Serve(l); err != nil {
                return err
        }
        return nil
}

**Comment by ym2049** [comment]
简化代码：
```
func OnRequest(ctx context.Context, conn netpoll.Connection) error {
        defer conn.Close
        r := bufio.NewReaderSize(ch, 1024)
        for {
                conn.SetReadDeadline(time.Now().Add(5*time.Second))
                header := make([]byte, 4)
                _, err := io.ReadFull(r, header)
        		if err != nil {
                	return err //resource temporarily unavailable
        		}

                conn.SetReadDeadline(time.Now().Add(5*time.Second))
        		body := make([]byte, conv2Length(header))
        		_, err := io.ReadFull(r, body)
        		if err != nil {
                	return err  //resource temporarily unavailable
        		}
        		//handle body
        }
        return nil
}
func bootstrapServer() error {
        el, err := netpoll.NewEventLoop(OnRequest)
        if err != nil {
                return err
        }
        l, err := net.Listen()
        if err != nil {
                return err
        } 
        if err := el.Serve(l); err != nil {
                return err
        }
        return nil
}
```

**Comment by joway** [comment]
I will debug it, but I recommend you to use No Copy API rather than io.ReadFull().

Here is a example :
https://github.com/cloudwego/netpoll-examples/blob/main/codec/rw.go#L37
https://www.cloudwego.io/docs/netpoll/getting-started/#3-use-nocopy-api
