### ISSUE TITLE
如何在多个协程里读写Connecion？

### ISSUE THREAD

**Issue by chenjianfei2017** [cloudwego/netpoll#254]
**// Connection supports reading and writing simultaneously,
// but does not support simultaneous reading or writing by multiple goroutines.**

Connection接口看到这个注释
是否意味着不能在多个协程中操作Connection？
比如：
```
{
    // 协程1
    connection.Writer().WriteString("string")
}

{
    // 协程2
    connection.Writer().WriteString("string2")
}
```

**Comment by chenjianfei2017** [comment]
是否有其他解决方案，这种场景还挺常见。
比如一个协程用原生的write，一个协程用netpoll的接口，能否解决上面的问题

```
{
    // 协程1
    connection.Write("string")
}

{
    // 协程2
    connection.Writer().WriteString("string2")
}
```

**Comment by chenjianfei2017** [comment]
或者通过加锁的方式是否可以
```
{
    // 协程1
    lock()
    connection.Writer().WriteString("string")
    unlock()
}

{
    // 协程2
    lock()
    connection.Writer().WriteString("string2")
    unlock()
}
```

**Comment by joway** [comment]
> 比如一个协程用原生的write，一个协程用netpoll的接口，能否解决上面的问题

不行。

你可以用加锁的方式实现。这里的问题不在于“功能”，而在于这个本身就是不可控的，你加锁实现只是保证了写入是安全的。但是你自己也不知道真的写入时候顺序是怎么样的。当然如果你不在乎顺序的话就没事
