### ISSUE TITLE
需要连接建立以后执行一次逻辑

### ISSUE THREAD

**Issue by ponecrazy** [cloudwego/netpoll#255]
看代码中有connection.SetOnConnect方法但是似乎没有通过接口引出来，只能通过server的opt引入
为什么不提供抽象方法引出

**Comment by joway** [comment]
因为只有server才有被动创建连接这么一说。dialer 你是自己主动创建连接的，你自己执行你需要做的事情就行了，不需要回调函数

**Comment by ponecrazy** [comment]
好的谢谢，你说的有道理，我这里场景比较特殊，钻牛角尖了
