### ISSUE TITLE
客户端使用OnRequest时无法控制context初始化

### ISSUE THREAD

**Issue by ponecrazy** [cloudwego/netpoll#257]
`SetOnRequest(on OnRequest)` 
`type OnRequest func(ctx context.Context, connection Connection) error`
dial的conn 无法介入 OnRequest接收到的ctx 的创建和初始化

**Comment by joway** [comment]
其实最早 OnRequest 是给 Server 类型的连接使用的。能说下你什么场景会需要 client 创建的连接还需要手动控制 Ctx 吗？

**Comment by joway** [comment]
long time no reply
