### ISSUE TITLE
need reuse connection

### ISSUE THREAD

**Issue by cea5** [cloudwego/netpoll#258]
I need to do benchmark for mqtt broker test. But when using netpoll client tcp connection to create mqtt connection, netpoll can't reuse **same** tcp connection to create multiple mqtt connection. 
(mqtt lib: [https://github.com/eclipse/paho.golang](https://github.com/eclipse/paho.golang))

Using java netty can satisfy my need.

So can netpoll add this feature or is there another way to do this?

**Comment by joway** [comment]
“can't reuse same tcp connection to create multiple mqtt connection.” 

it depends on your usage. Are you using netpoll dialer API?

**Comment by cea5** [comment]
yes, i'm using client DialConnection api.
need eventloop is client side.

**Comment by joway** [comment]
Netpoll dont control the reuse connection logic, it should reuse by yourself.
