### ISSUE TITLE
Poll Manager should be initialized lazily

### ISSUE THREAD

**Issue by ItalyPaleAle** [cloudwego/netpoll#259]
**Describe the bug**

This package includes an `init()` method which is executed when the package is imported, even if not used:

https://github.com/cloudwego/netpoll/blob/4b09897f5b07067929002b614c720924c6396f6e/poll_manager.go#L44-L51

We import this package in Dapr to allow using Kitex as a binding. Using Kitex is optional, but because of this `init()` method allocating a poll manager, it causes additional goroutines (and more heap allocations) for every user.

**To Reproduce**

1. Import the package
2. Observe that a number of goroutines is automatically created

**Expected behavior**

Poll Manager should be initialized lazily, only when first needed.

**Comment by joway** [comment]
@ItalyPaleAle Thanks for reporting. I think it's make sense. We will implement lazy initialization in next version.

**Comment by joway** [comment]
https://github.com/cloudwego/netpoll/pull/306
