### ISSUE TITLE
你们内部版本改了内核，开源版本怎么用呢？

### ISSUE THREAD

**Issue by gcnyin** [cloudwego/netpoll#26]
https://www.infoq.cn/article/fea7chf9moohbxbtyres

> 于是，字节跳动框架组和字节跳动内核组合作，由内核组提供了同步的接口：当调用 sendmsg 的时候，内核会监听并拦截内核原先给业务的回调，并且在回调完成后才会让 sendmsg 返回。这使得我们无需更改原有模型，可以很方便地接入 ZeroCopy send。同时，字节跳动内核组还实现了基于 unix domain socket 的 ZeroCopy，可以使得业务进程与 Mesh sidecar 之间的通信也达到零拷贝。

总不至于让大家用你们内部维护的内核吧？

**Comment by lsjbd** [comment]
这部分涉及到的内容目前还未开源。字节内核组也在积极推动将相关改进 patch 给 kernel，如果将来可用了，我们也会将 kitex、netpoll 的相关代码开源。

**Comment by gcnyin** [comment]
> 这部分涉及到的内容目前还未开源。字节内核组也在积极推动将相关改进 patch 给 kernel，如果将来可用了，我们也会将 kitex、netpoll 的相关代码开源。

那你们的benchmark是基于哪个版本做的呢？

**Comment by Hchenn** [comment]
> > 这部分涉及到的内容目前还未开源。字节内核组也在积极推动将相关改进 patch 给 kernel，如果将来可用了，我们也会将 kitex、netpoll 的相关代码开源。
> 
> 那你们的benchmark是基于哪个版本做的呢？

benchmark 就是当前开源的版本，不涉及没开源的部分
