### ISSUE TITLE
wrong comments in connection_impl.go

### ISSUE THREAD

**Issue by ganlvtech** [cloudwego/netpoll#263]
https://github.com/cloudwego/netpoll/blob/35639d24098575e37477e4733d1c8ff817ef2758/connection_impl.go#L98-L101

Should be

```go
// Next implements Reader.
```

**Comment by joway** [comment]
In fast, Connection included the original Reader interface

**Comment by ganlvtech** [comment]
> In fast, Connection included the original Reader interface

`Connection` interface doesn't include `Reader` interface. It only has a `Reader()` method returns `Reader`.

https://github.com/cloudwego/netpoll/blob/35639d24098575e37477e4733d1c8ff817ef2758/connection.go#L29-L70
