### ISSUE TITLE
Run netpoll on Windows: a netpoll interface implement with standard go net

### ISSUE THREAD

**Issue by ganlvtech** [cloudwego/netpoll#266]
https://github.com/ganlvtech/std-netpoll

仅供在 Windows 下调试使用，可以直接使用 hertz 或 kitex，不用担心编译问题。

## Usage

```bash
go mod edit -replace github.com/cloudwego/netpoll=github.com/ganlvtech/std-netpoll@develop
```

因为代码差异很大，所以没法提交 Pull Request

**Comment by ganlvtech** [comment]
https://github.com/cloudwego/netpoll/compare/develop...ganlvtech:std-netpoll:develop

**Comment by joway** [comment]
@ganlvtech Hi, 我看你一直在更新这个分支。其实你没必要把老的代码删掉？你可以通过 go build tag，让windows 编译的时候不走原先的逻辑

**Comment by ganlvtech** [comment]
@joway 之后我会逐步把 netpoll 的代码加回来的，最后再 squash。
我不是把老代码删掉。我是直接新开了一个文件夹，先把接口都复制过来，然后写实现。然后再一点一点把 netpoll 的代码加回来。
在原来的基础上改的话，epoll 和 std 的实现方式差异比较大，我有点 hold 不住。而且有些功能做不了，或者有些 option 在 go net 这种阻塞式模型没必要，直接改原来的代码可能扒不干净。

**Comment by joway** [comment]
@joway ok
