### ISSUE TITLE
是否能够让底层共享模型建立在IPC模式下呢，比如mmap共享模型上

### ISSUE THREAD

**Issue by carolove** [cloudwego/netpoll#27]
不知道这个netpoll的进程间通讯，是否可以提供对进程间通讯IPC的支持，特别是建立在mmap的sharedBuffer的基础上，来完成应用与sidecar的网络模型数据关联

**Comment by Hchenn** [comment]
很好的想法，我们已经在尝试了，可能还需要一些时间，感谢～

**Comment by YangruiEmma** [comment]
@carolove 我们已经支持了shm-ipc，目前在内部使用，kitex也有对shm-ipc的扩展，后续会开源出来的
