### ISSUE TITLE
对于TLS的支持，大概什么时候能发布呢？

### ISSUE THREAD

**Issue by RPCheung** [cloudwego/netpoll#275]
现在是否有，临时的兼容方案呢？

**Comment by RPCheung** [comment]
现在是否有，临时的兼容方案呢？

**Comment by joway** [comment]
@RPCheung 在 netpoll 不深度支持 TLS 的情况下，性能和 go 官方 net 库不会有什么区别。所以目前所谓的兼容方案就是你这种情况下可以直接用 go 官方 net。
