### ISSUE TITLE
ignore onRequest return value is not correct

### ISSUE THREAD

**Issue by ahfuzhang** [cloudwego/netpoll#288]
see: https://github.com/cloudwego/netpoll/blob/cf96b810bf76819dc2e78f3218d192fe47f99b64/connection_onevent.go#L161

This line ignore the return error of onRequest.
I think when use return a error of onRequest, the framework should close socket fd.

Thanks.

**Comment by joway** [comment]
https://github.com/cloudwego/netpoll/blob/cf96b810bf76819dc2e78f3218d192fe47f99b64/eventloop.go#L93

It should close connection by yourself. currently, netpoll dont use the return error of OnRequest. see the comment.
