### ISSUE TITLE
几个问题想请教一下

### ISSUE THREAD

**Issue by MeteorsLiu** [cloudwego/netpoll#295]
我是Golang的初学者，然后最近开发遇到一些和贵项目相同的问题，所以想来请教下。

Golang Sysmon会随时打断SYSCALL，也就是sendmsg可能会返回EINTR错误，或者返回已写入的数据量（有可能是没写入完的），但是我看netpoll的sendmsg不确保写入完整，反而直接返回错误，不进行任何处理，而下一次write直接Flush了缓冲区，有点没看明白，问一下这样处理是有什么技巧吗

如果因为SYSCALL被打断导致数据不完整，那不是会导致数据包发送出现错误么？

其次我看到贵项目也准备使用Zero Copy，然后想请教一下，如何才能保证内存在数据包被发送后才能被释放呢。

如上，这两个问题卡住了。如果能回答，不胜感激。

**Comment by joway** [comment]
@MeteorsLiu 因为 event poller 会异步把数据持续写完。netpoll 的所有socket都是 non blocking 的

**Comment by markity** [comment]
1. 只有阻塞住了才会被信号打断返回EINTERP，非阻塞的fd读写永远不会阻塞。这里补充一下，只有慢系统调用才会被阻塞，read/write可能是慢系统调用，取决于fd对应的是什么设备。比如磁盘文件的read/write永远不会被阻塞。
2. close callback会closeBuffer

```go
func (c *connection) initFinalizer() {
	c.AddCloseCallback(func(connection Connection) (err error) {
		c.stop(flushing)
		c.operator.Free()
		if err = c.netFD.Close(); err != nil {
			logger.Printf("NETPOLL: netFD close failed: %v", err)
		}
		c.closeBuffer()
		return nil
	})
}
```

**Comment by MeteorsLiu** [comment]
很抱歉打扰您了，谢谢解答
