### ISSUE TITLE
后续是否可能支持 windows

### ISSUE THREAD

**Issue by Singularity0909** [cloudwego/netpoll#30]
kitex 项目依赖 netpoll 在 windows 不能编译 : (

**Comment by Hchenn** [comment]
暂时没计划

**Comment by Singularity0909** [comment]
好吧 =。=



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月9日(星期一) 晚上6:56
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cloudwego/netpoll] 后续是否可能支持 windows (#30)





 
暂时没计划
