### ISSUE TITLE
add `net.Listen` compatible `netpoll.Listen`

### ISSUE THREAD

**Issue by qsliu2017** [cloudwego/netpoll#301]
**Is your feature request related to a problem? Please describe.**
`netpoll.CreateListener` has the same interface as `net.Listen`, but there is no `netpoll.Listen`

**Describe the solution you'd like**
rename `netpoll.CreateListener` to `netpoll.Listen`, or add a wrapper function

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by joway** [comment]
@qsliu2017 it should be better that use "netpoll.Listen" at the beginning, but for now, it's hard to rename the Public API. What's problem you meet with current interface?

**Comment by joway** [comment]
@qsliu2017 but it will let package have 2 same function public fuction... It's not a frequently-used function, and it not a Interface type so will not let anything break. So I think it's not worth to change it only for keep same with go net.
