### ISSUE TITLE
[Goleaks] Found unexpected goroutines in netpoll error

### ISSUE THREAD

**Issue by roma-glushko** [cloudwego/netpoll#305]
**Describe the bug**

I want to use [goleak](https://github.com/uber-go/goleak) in my CI to find suspicious code that may lead to different sorts of leaks.
When I enabled it for a Hertz-based server, goleaks resports this error:

<img width="842" alt="Screenshot 2024-02-04 at 15 42 41" src="https://github.com/cloudwego/netpoll/assets/9402690/3fc80a6d-fd8f-43e4-b9fa-43466c597387">

The error is reported even when the standard transport is used instead of netpoll because the netpoll seems to be a dependency for hertz somehow 🤔 

**To Reproduce**

1. Go to https://github.com/einstack/glide
2. Uncomment the test in [leak_test.go](https://github.com/EinStack/glide/blob/develop/leak_test.go)
3. Run `make test` to run the whole test suit (or you may run just that specific test)

**Expected behavior**
Goleaks doesn't see any issues with netpoll (and hertz in general).

**Screenshots**
See above.

**Desktop (please complete the following information):**
 - OS: MacOS

**Additional context**

**Comment by joway** [comment]
@roma-glushko Hi, this is because netpoll use init() function to init poller, which will create a background goroutine. I will change it to lazy init.

**Comment by roma-glushko** [comment]
@joway thank you for fixing that!
