### ISSUE TITLE
flush函数中调用sendmsg函数的参数为什么是false && c.supportZeroCopy？

### ISSUE THREAD

**Issue by XiaoYi-byte** [cloudwego/netpoll#322]
**Describe the bug**
根目录下的connection_impl.go中的flush函数中调用sendmsg函数的参数为什么是false && c.supportZeroCopy？这里不是显然是false吗？在sendmsg函数也没有使用这个参数，是目前还没有实现这一部分吗？

**Screenshots**
![image](https://github.com/cloudwego/netpoll/assets/72679319/da3dc72d-3f3d-47bc-a18a-e2ef8bbb37d2)

**Desktop (please complete the following information):**
 - Version [v0.6.0]

**Comment by joway** [comment]
@XiaoYi-byte 因为依赖内核支持。这不是一个通用性的 feature ，所以相当于直接disable了这个
