### ISSUE TITLE
为什么netpoll在读取数据当数据不足的时候, 需要通过一个channel去阻塞住gorutine

### ISSUE THREAD

**Issue by leslie-fei** [cloudwego/netpoll#328]
有一点疑惑, 如果这里数据不足阻塞读的话跟标准库的区别
https://github.com/cloudwego/netpoll/blob/67865906a4ef908acf0323969d59688916e59173/connection_impl.go#L397

**Comment by joway** [comment]
@leslie-fei 在有数据要读的时候，至少协程模型确实和标准库区别不大，他们协程模型有区别的地方在于没数据要读的时候，标准库要常态维护一个g，netpoll 不需要。当然使用者也可以用 conn.Next(conn.Reader().Len()) 有多少读多少。
