### ISSUE TITLE
onRequest task里面为什么需要重新上锁呢？

### ISSUE THREAD

**Issue by halodou** [cloudwego/netpoll#33]
https://github.com/cloudwego/netpoll/blob/5607dcbce465c6c75e53fa346da356df96bfb38b/connection_onevent.go#L111
是否仅当 c.Reader().Len() <= 0 进行一次unlock即可，可以减少一次增删锁的开销，task中重新上锁的原因是什么呢？

**Comment by Hchenn** [comment]
c.onRequest 会被频繁触发，而 task 要保证有且只有一个。如果 unlock 同时有新的数据到来，并在 90 行没有抢到锁，将导致没有任何 task 可以处理新数据。

**Comment by halodou** [comment]
嗯嗯，这种场景如下处理是否会更好呢？
`
if c.Reader().Len() > 0 {
	goto START
} else {
        c.unlock(processing)
        // Double check
	if c.Reader().Len() > 0 && c.lock(processing) {
		goto START
	}
}`

**Comment by Hchenn** [comment]
这不是凭空多一次判断吗，101 行和106 行已经说明了 len<0

**Comment by halodou** [comment]
嗯嗯，我可能理解有点问题或者没有表述清楚，我再复述一下吧：
- 在streaming的场景下，如果可以在一个task里面处理完一次handler之后，先判断reader.len再解锁，应该会比先解再判断len然后再重新抢锁要高效一点（多一次条件判断，但少一次加减锁开销）；
- 先判断len后解锁可能会导致开头你说的没有task能抢到锁的场景，所以在释放锁后重新校验一下len就好了（与当前实现一致）；

**Comment by halodou** [comment]
嗯嗯，我可能理解有点问题或者没有表述清楚，我再复述一下吧：
- 在streaming的场景下，如果可以在一个task里面处理完一次handler之后，先判断reader.len再解锁，应该会比先解再判断len然后再重新抢锁要高效一点（多一次条件判断，但少一次加减锁开销）；
- 先判断len后解锁可能会导致开头你说的没有task能抢到锁的场景，所以在释放锁后重新校验一下len就好了（多一次判断，其余与当前实现一致）；

**Comment by halodou** [comment]
嗯嗯，我可能理解有点问题或者没有表述清楚，我再复述一下吧：
- 在streaming的场景下，如果可以在一个task里面处理完一次handler之后，先判断reader.len再解锁，应该会比先解再判断len然后再重新抢锁要高效一点（多一次条件判断，但少一次加减锁开销）；
- 先判断len后解锁可能会导致开头你说的没有task能抢到锁的场景，所以在释放锁后重新校验一下len就好了（与当前实现一致）；

**Comment by Hchenn** [comment]
101 行的 for 循环都退出了，还不能证明 len<0 吗？再加一次判断的意义是？

**Comment by halodou** [comment]
哦哦，你说的对，我看错了
