### ISSUE TITLE
Bug: Writer的MallocLen()方法返回不正确的问题

### ISSUE THREAD

**Issue by JHue58** [cloudwego/netpoll#334]
目前有一个需求，需要计算Connection.Writer().Flush()的字节数，用到了MallocLen，但是配合Append使用会出现一些问题，
例如下面这个测试用例是不能通过的。

``` go
length := 100
buf := make([]byte, length)
lb := netpoll.NewLinkBuffer(1024)
lb.WriteBinary(buf)

lb.Flush() // 注释掉这行就能通过

newLb := netpoll.NewLinkBuffer(1024)
newLb.Append(lb)
before := newLb.MallocLen()
newLb.Flush()
after := newLb.MallocLen()
assert.Equal(t, length, before-after)
assert.Equal(t, length, newLb.Len())
```

排查后发现Append方法在重新计算MallcoLen时，会直接+=入参buf的MallocLen()，忽略了入参buf已经被flush的情况。

```go
bufLen, bufMallocLen := buf.Len(), buf.MallocLen()
if bufLen+bufMallocLen <= 0 {
    return nil
}

// code

if bufLen > 0 {
    b.recalLen(bufLen)
}
b.mallocSize += bufMallocLen
```
改成这样可以解决这个问题，但是目前尚未清楚会不会引起其他的bug
```go
bufLen, bufMallocLen := buf.Len(), buf.MallocLen()
if bufLen+bufMallocLen <= 0 {
    return nil
}
if bufMallocLen <= 0 {
    bufMallocLen=bufLen
}
// code
```

**Comment by JHue58** [comment]
还是说这里是设计行为？本意是想"继承"入参buf的状态，但我个人认为不太妥当。
把oldBuf写入到一个newBuf，应该要newBuf在调用flush后才能读到这段数据。
而不是写入完我不调用flush就能读到oldBuf这段数据，感觉有点奇怪。

**Comment by joway** [comment]
@JHue58 Append 操作你可以认为是 merge 了两个平等的 linkbuffer， 即链表每个节点的状态都是各自独立的。这里的注视也有这个类似的意思：
![image](https://github.com/cloudwego/netpoll/assets/8353464/219d5a34-6969-43a4-a545-c675eef7ae34)

**Comment by JHue58** [comment]
> @JHue58 Append 操作你可以认为是 merge 了两个平等的 linkbuffer， 即链表每个节点的状态都是各自独立的。这里的注视也有这个类似的意思： ![image](https://private-user-images.githubusercontent.com/8353464/335927424-219d5a34-6969-43a4-a545-c675eef7ae34.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczOTI1OTQsIm5iZiI6MTcxNzM5MjI5NCwicGF0aCI6Ii84MzUzNDY0LzMzNTkyNzQyNC0yMTlkNWEzNC02OTY5LTQzYTQtYTU0NS1jNjc1ZWVmN2FlMzQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDNUMDUyNDU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjAxMGQ1Zjk4Y2ZiNDI1YjkwZTdjZThjM2E4ZmNhMTRjMmI4NmJmNzlhYTA1Yjc4NzRlNDZjNWZjZmZjMGQ0NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.3X-JJoTR07UzB1eeWKdLuVqnV4o74k5TzhGmpBnu5sM)

那有没有办法实现conn.Writer().Flush()的同时返回flush字节数的需求？netpoll.Writer没有Len方法就很头疼

**Comment by joway** [comment]
@JHue58 你能描述下你什么场景需要这个吗？比如在 kitex 的使用场景里，flush写入了多少bytes，实际上上层是完全知道的。不需要靠flush函数返回。

**Comment by JHue58** [comment]
> @JHue58 你能描述下你什么场景需要这个吗？比如在 kitex 的使用场景里，flush写入了多少bytes，实际上上层是完全知道的。不需要靠flush函数返回。

比如我这边暴露了一个AppenToConn(netpoll.Writer)的接口给外部，连接的Flush是由内部的另一个协程进行的，就像ShardQueue一样，内部的协程无法知道写入了多少bytes

**Comment by joway** [comment]
@JHue58 你也可以自己实现一个 netpoll.Writer 的接口，内部封装下来实现你要的能力。以目前的netpoll的设计已经暴露接口来说，flush的返回值肯定是无法修改的了

**Comment by JHue58** [comment]
> @JHue58 你也可以自己实现一个 netpoll.Writer 的接口，内部封装下来实现你要的能力。以目前的netpoll的设计已经暴露接口来说，flush的返回值肯定是无法修改的了

嗯，目前看来这能这么做了。
另外我想请教一下，WriteBuffer设计成Merge而不是将一个LinkBuffer的所有节点写入到另一个LinkBuffer中，是有什么考量吗？

**Comment by joway** [comment]
网络库主要面向的是有界协议，以grpc为例，一个frame是对应为一个 linkbuffer，而一个frame如果已经写入完毕，那么它就调用buf.Flush() ，是一个完成的frame数据。对于连接发送来说，每个frame都是平等的，谁先写后写也是一样的，不存在说后面的linkbuffer要影响前面linkbuffer的问题

**Comment by JHue58** [comment]
> @JHue58 网络库主要面向的是有界协议，以grpc为例，一般在这个设计里，是一个frame是对应为一个 linkbuffer，而一个frame如果已经写入完毕，那么它就调用buf.Flush() ，是一个完成的frame数据。对于连接发送来说，每个frame都是平等的，谁先写后写也是一样的，不存在说后面的linkbuffer要影响前面linkbuffer的问题

把这个frame写入连接时，一般都会调用conn.Writer().Append()吧，假设把这个方法包装成WriteFrame(wr netpoll.Writer)，如果是类似shardQueue的异步flush，这时候对连接来说，就不知道Append进去了多少字节，进而无法在连接层面控制一次性flush的bytes大小。
只能在WriteFrame里面将writer重新断言成linkbuffer，或者是断言成interface{Len()int}，才有办法做到这一点。

**Comment by joway** [comment]
我的意思是，你暴露给你的用户的接口，不一定要是 netpoll.Writer ，也可以是你自己实现的一个类似linkbuffer的结构，比如这里的 yourFramer， 它实现了 netpoll.Writer 的接口。

```
func (c *yourconn)WriteFrame(fr yourFramer) {
    c.written += fr.Len()
    c.netpoll_conn.Wriler().Append(fr)
}
```

yourFramer 可以继承 LinkBuffer ，然后你劫持要劫持的函数比如 Flush，就能实现你自己的功能了

**Comment by JHue58** [comment]
> @JHue58 我的意思是，你暴露给你的用户的接口，不一定要是 netpoll.Writer ，也可以是你自己实现的一个类似linkbuffer的结构，比如这里的 yourFramer， 它实现了 netpoll.Writer 的接口。
> 
> ```
> func (c *yourconn)WriteFrame(fr yourFramer) {
>     c.written += fr.Len()
>     c.netpoll_conn.Wriler().Append(fr)
> }
> ```
> 
> yourFramer 可以继承 LinkBuffer ，然后你劫持要劫持的函数比如 Flush，就能实现你自己的功能了

好的了解了，受教了！
