### ISSUE TITLE
locked和freelocked 这2个字段为什么不放在一起

### ISSUE THREAD

**Issue by dxasu** [cloudwego/netpoll#365]
https://github.com/cloudwego/netpoll/blob/8a1f5597a92075008c4c9ed697d7db8070e38af1/fd_operator_cache.go#L37

```
type operatorCache struct {
	locked int32
	first  *FDOperator
	cache  []*FDOperator
	// freelist store the freeable operator
	// to reduce GC pressure, we only store op index here
	freelist   []int32
	freelocked int32
}
```

locked和freelocked 这2个字段为什么要分开放呢？？导致结构体，从64字节变成72字节，刚刚超出了一个缓存行的大小。
如果是为了2个锁相互不干扰，但是freelist本身也处于第一个缓存行里。

**Comment by joway** [comment]
@dxasu 没有为什么，原因其实是因为free是后面新加的字段。有兴趣可以提个pr换到前面并写明注释～
