### ISSUE TITLE
QPS chart is misleading

### ISSUE THREAD

**Issue by nikolaydubina** [cloudwego/netpoll#37]
https://github.com/cloudwego/netpoll#performance

"Concurrent Performance (Echo 1KB): QPS" is misleading. It starts at Y=210,000. This library is only 30,000/250,000 is 10% faster.

Please use same Y offset 0 as rest of the graphs.

Do admit that you say it is 110% of `net` package QPS. Thanks for being accurate there!

Thanks for open sourcing this too!

**Comment by Hchenn** [comment]
Thanks for the reminder, this is a processing error, we will correct it later.
