### ISSUE TITLE
How to read up to \n

### ISSUE THREAD

**Issue by da-tai** [cloudwego/netpoll#4]
Is there anyway to read a packet up to `\n` similar to `conn.Reader().Next()`?

For example, using net package, I use 

`bufio.NewReaderSize(conn, 1024).ReadLine()`

for 

`{"id":2,"method":foobar","params":[]}\n {"id":3,"method":"foobar","params":["foobar.foo",""]}\n`

**Comment by Hchenn** [comment]
No rich API yet, and we are already under development, and we expect to support it on v0.1.0
