### ISSUE TITLE
循环依赖问题

### ISSUE THREAD

**Issue by svnshing** [cloudwego/netpoll#40]
connection.go和netpoll.go在ide中无法导入包，个人感觉是这2个文件件存在循环依赖引用问题，想确认是否是这个原因

**Comment by svnshing** [comment]
![thumbnail_e54fd018a26ca84182d183394c8e3b37](https://user-images.githubusercontent.com/19359551/132655287-5b7dffb2-80b3-4f4c-b729-2428031d7283.png)

![thumbnail_73d96e25731f9c4aa3884346f28b8bd9](https://user-images.githubusercontent.com/19359551/132655307-1be05dcf-9b1c-4e8d-8484-311dad4353f2.png)

**Comment by lsjbd** [comment]
依赖关系的单元是「包」或者「模块」，而不是文件。这点和 C 或者 C++ 是不一样的。你在 IDE 中无法导入包，应该是别的原因，建议换个思路排查下。

**Comment by svnshing** [comment]
> 依赖关系的单元是「包」或者「模块」，而不是文件。这点和 C 或者 C++ 是不一样的。你在 IDE 中无法导入包，应该是别的原因，建议换个思路排查下。

ok，谢谢大佬解答

**Comment by directorfan** [comment]
我也遇到了同样的问题，请问有解决方法吗

**Comment by aschenmaker** [comment]
新版的goland的问题，我也有遇到过。
没有解决，换了vscode，没有问题
