### ISSUE TITLE
syscall.EpollCtl和syscall.RawSyscall6(syscall.SYS_EPOLL_CTL,...)没区别吧？

### ISSUE THREAD

**Issue by betazk** [cloudwego/netpoll#43]
使用的go版本：go 1.17.1 linux/amd64
我看系统调用也直接有Epoll相关的接口，这个和netpoll中采用syscall.RawSyscall6有区别吗？
还是说只是因为syscall.EpollCtl这种是被runtime管理的，效率上会有所降低？谢谢

**Comment by Hchenn** [comment]
是的。syscall.EpollCtl 实现直接使用的 syscall.Syscall, 相比 syscall.RawSyscall 实现上多了 enterruntime 和 exitruntime 两步，效率会略低。
