### ISSUE TITLE
我在运行示例代码的时候报的netpoll找不到这些，升级了go版本还是这个问题，请问我该怎么做谢谢

### ISSUE THREAD

**Issue by atlarge800** [cloudwego/netpoll#47]
..\..\go1.17.1\pkg\mod\github.com\cloudwego\netpoll@v0.0.3\connection.go:59:18: undefined: OnRequest
..\..\go1.17.1\pkg\mod\github.com\cloudwego\netpoll@v0.0.3\connection_impl.go:30:2: undefined: netFD
..\..\go1.17.1\pkg\mod\github.com\cloudwego\netpoll@v0.0.3\connection_impl.go:40:19: undefined: barrier
..\..\go1.17.1\pkg\mod\github.com\cloudwego\netpoll@v0.0.3\connection_impl.go:41:19: undefined: barrier
..\..\go1.17.1\pkg\mod\github.com\cloudwego\netpoll@v0.0.3\connection_impl.go:252:32: undefined: Conn
..\..\go1.17.1\pkg\mod\github.com\cloudwego\netpoll@v0.0.3\connection_impl.go:252:46: undefined: OnPrepare
..\..\go1.17.1\pkg\mod\github.com\cloudwego\netpoll@v0.0.3\connection_impl.go:272:38: undefined: Conn
..\..\go1.17.1\pkg\mod\github.com\cloudwego\netpoll@v0.0.3\connection_onevent.go:48:39: undefined: OnRequest
..\..\go1.17.1\pkg\mod\github.com\cloudwego\netpoll@v0.0.3\connection_onevent.go:71:40: undefined: OnPrepare
..\..\go1.17.1\pkg\mod\github.com\cloudwego\netpoll@v0.0.3\net_sock.go:41:116: undefined: netFD
..\..\go1.17.1\pkg\mod\github.com\cloudwego\netpoll@v0.0.3\net_sock.go:41:116: too many errors

**Comment by betazk** [comment]
事例代码可否贴一下？然后最好把运行的系统及运行方式也贴一下，可以方便排查原因

**Comment by joway** [comment]
@atlarge800 目前不支持 Windows 操作系统，建议可以换到 docker 或者 linux 虚拟机中运行

**Comment by atlarge800** [comment]
@YangruiEmma @betazk @joway 谢谢，我确实使用的是windows系统，跑的是Cloudwego官方文档的示例代码git clone https://github.com/cloudwego/kitex-examples.git 中的hello项目，我换linux试一下，可以正常跑了，谢谢

**Comment by GreenSharpHuang** [comment]
不支持windows 那一定要在linux中开发吗？

**Comment by YangruiEmma** [comment]
> 不支持windows 那一定要在linux中开发吗？

使用Netpoll暂时是的
