### ISSUE TITLE
WriteBuffer返回值n语义是什么？

### ISSUE THREAD

**Issue by heydoer** [cloudwego/netpoll#48]
https://github.com/cloudwego/netpoll/blob/3304c59ced90fdf1984e0895b1531f9d35938c50/nocopy_linkbuffer.go#L364
看起来这个返回值蘅为零值

**Comment by Hchenn** [comment]
感谢，n 没有意义，这里是代码迭代中疏忽了，后续我们移除它。
原因：最初的 WriteBuffer 是默认执行 Flush 方法的，返回 n 代表 Flush 后提交的总长度。但后续迭代中，结耦了语义，WriteBuffer 不再执行 Flush（改为由使用者主动执行），导致 n 失去了原来的意义。
