### ISSUE TITLE
LinkBuffer的readBinary方法

### ISSUE THREAD

**Issue by betazk** [cloudwego/netpoll#51]
我看注释里说是不能使用mcache，理由是无法进行回收。这个不太理解，请问这个方法和其他读取数据的方法（例如：Next）在空间回收上有区别吗？感谢
nocopy_linkbuffer.go#206

**Comment by Hchenn** [comment]
不考虑具体实现，单从接口语义上解释：

当进行 Decode(解码) 时，总要保证最后解码得到的 request/response 不依赖 I/O 缓存。

举例说明：
1. 如果我们要解析 `req := struct{ Msg []byte }`，那么流程伪代码应该是：
`buf := make([]byte, len); n, _ := net.Conn.Read(buf); req.Msg = append([]byte{}, buf[:n]...)`
可以看出 req.Msg 不是直接持有 buf[:n], 因为 buf 需要被 I/O 复用，而 req 是由上层使用者控制，生命周期不可控。这里需要 copy buf[:n]。

2. 但是如果定义 req.Msg uint32, 那么解析伪代码则是：
`req.Msg = binary.BigEndian.Uint32(buf[:4)`
这里并没有 copy buf[:n]，因为 uint32 一定不会持有 buf 的原地址。

对应上述两个例子：
1. ReadBinary 对应了例子 1，语义上表明了返回的 []byte 是从 I/O buffer 拷贝过的，上层使用者可以持有任意的生命周期，而不影响底层 buffer 的复用。
2. Next 则对应了例子 2，语义上表明了返回值是 buffer 的原地址切片，因此一般用来解析 int/bool 等字段值。

**Comment by betazk** [comment]
非常感谢耐心回答。那就是说其实两个方法更多还是在使用的场景上的区别导致一个是从mcache分配，一个是直接make方式分配。使用mcache更多的还是为类似int/bool等字段服务的，对吗？Next的功能其实也是可以使用ReadBinary替代，只是为了优化当需要解析的内容为int/bool等字段的时候资源开销，从而约定式的采用Next，对吧？

**Comment by Hchenn** [comment]
> 非常感谢耐心回答。那就是说其实两个方法更多还是在使用的场景上的区别导致一个是从mcache分配，一个是直接make方式分配。使用mcache更多的还是为类似int/bool等字段服务的，对吗？Next的功能其实也是可以使用ReadBinary替代，只是为了优化当需要解析的内容为int/bool等字段的时候资源开销，从而约定式的采用Next，对吧？

是的
