### ISSUE TITLE
Example link in README.md not work

### ISSUE THREAD

**Issue by zqkgo** [cloudwego/netpoll#55]
https://github.com/cloudwego/netpoll-benchmark
404 Not Found
Please fix it, or remove if not exist.

**Comment by Hchenn** [comment]
Already applied for public, under review, may be able to see next month.

**Comment by MasoudAkb** [comment]
Also get error 404 when try to access 
[](https://github.com/cloudwego/netpoll-examples)
to study the examples

**Comment by Hchenn** [comment]
https://github.com/cloudwego/netpoll-benchmark
