### ISSUE TITLE
Memory Issue when testing splice

### ISSUE THREAD

**Issue by da-tai** [cloudwego/netpoll#65]
Testing Splice with over 1000 Concurrent connections has high memory usage. Even after all 1000 clients are closed, the memory usage is still high. Here is a pprof image of heap for over 300 seconds. 
![profile001](https://user-images.githubusercontent.com/137142/138998682-a2806c94-4464-4067-bb45-482c4907f08e.png)
.

**Comment by da-tai** [comment]
My code looks like this 
```
var eventLoop netpoll.EventLoop

func handler(ctx context.Context, conn netpoll.Connection) error {

    data, err := conn.Reader().ReadBinary(conn.Reader().Len())
        if err != nil {
		logging...
		return conn.Close()
	}
    ....business logic......
     conn.Reader().Release()
     remote := net.Dial(remote server)
     go func () {
         _, err := io.Copy(remote,conn)
      }
      io.Copy(conn,remote)
}
```

What I am noticing is on a specific VPS provider, I get the memory issue but on another, i don't.
Here is the flame graph of another. 

![profile002](https://user-images.githubusercontent.com/137142/140218359-a08d1bd6-54bb-47db-8044-3dcba72ddda1.png)

**Comment by Hchenn** [comment]
PS: The first graph is abbreviated as `Fig 1`, the second as `Fig 2`

I found that in the two graphs, the difference lies in the proportion of `netpoll(*LinkBuffer).growth`
The `handleTCPProxy` in `Fig 2` is `inlined` but not in `Fig 1`. Is there a difference here ?

Sorry for not finding other useful help.

**Comment by da-tai** [comment]
This is helpful thanks. I will reopen this issue if I find something more defined. 

Thanks again.
