### ISSUE TITLE
预期什么时候开始开源支持io_uring?

### ISSUE THREAD

**Issue by xj524598** [cloudwego/netpoll#77]
预期什么时候开始开源支持io_uring?

**Comment by Hchenn** [comment]
最近 2-4 个月左右吧，感谢关注 ～

**Comment by xj524598** [comment]
话说是否有微信群，手机app太多了，内存不足。。最近在调研servicemesh，想用netpoll作为网络库。我这边是一个互联网中厂，如果成功了 也可以给你们带来很多使用反馈

**Comment by Hchenn** [comment]
飞书群人多，建议可以使用网页版访问 https://bytedance.feishu.cn/messenger/
微信群见下面链接（有时效性）

**Comment by Hchenn** [comment]
![middle_img_v2_cd926fab-85b5-4d02-9369-95314fca886g](https://user-images.githubusercontent.com/26022685/143415541-3cc48fa7-aed0-4742-a012-5e5fdd857f51.jpg)

**Comment by WineChord** [comment]
是已经支持了还没开源，还是正在支持中呢？

**Comment by ii64** [comment]
我看到了README.md，liburing需要用CGO？

**Comment by Hchenn** [comment]
> 我看到了README.md，liburing需要用CGO？

不用啊，直接用 go 实现

**Comment by kelele67** [comment]
插个眼，期待~

**Comment by supermario1990** [comment]
希望早点支持，感谢

**Comment by alviroiskandar** [comment]
mengghadeeh

**Comment by hiqsociety** [comment]
hope to see it happen

**Comment by joway** [comment]
@manchurio 我们内部调研，uring 对 RPC 场景的改善很少，尤其是小包场景。如果netpoll支持 uring，代码改造挺大，收益却不大，所以目前暂缓在现有代码基础上，支持 uring 了。但是会在后面的大版本重构中，把这个功能考虑进来。

**Comment by someview** [comment]
> @manchurio 我们内部调研，uring 对 RPC 场景的改善很少，尤其是小包场景。如果netpoll支持 uring，代码改造挺大，收益却不大，所以目前暂缓在现有代码基础上，支持 uring 了。但是会在后面的大版本重构中，把这个功能考虑进来。

也就是说，对大包的场景改进比较大了，是这种意思吗

**Comment by joway** [comment]
@someview 包越大越有优势。
