### ISSUE TITLE
运行普通的server端demo有问题

### ISSUE THREAD

**Issue by xj524598** [cloudwego/netpoll#80]
![image](https://user-images.githubusercontent.com/26913796/143415047-eaba5130-f322-4ffc-88ba-fc6e293d0d62.png)
如上图：
d当我监听12345端口后，想请求下该端口查看是netpoll处理io事件流程，却发现监听端口始终无法启动，也没有任何报错。
之前曾经短暂启动成功过
下面是具体的code代码：

import (
	"context"
	"fmt"
	"github.com/cloudwego/netpoll"
	"time"
)

func main() {

	l, err := netpoll.CreateListener("tcp", ":12345")
	if err != nil {
		panic("监听错误")
	}
	eventLoop, _ := netpoll.NewEventLoop(
		//这个就是接收到io事件后处理的handler
		func(ctx context.Context, connection netpoll.Connection) error {
			fmt.Printf("收到请求了")
			return nil
		},
		netpoll.WithReadTimeout(time.Second))
	fmt.Printf("准备开始监听请求")
	eventLoop.Serve(l)
}

下面是我电脑的配置：

![image](https://user-images.githubusercontent.com/26913796/143415397-3b074a70-cbf4-44c3-bac0-aea1f233dcab.png)

**Comment by Hchenn** [comment]
你好像遇到了和 #52 相同的问题，貌似是触发了 golang 的某个 bug ?  

这个问题已经在 pr #54 中被修复，会在下周发布的 v0.0.5 中生效。

当前有两个手段来规避该问题：
1. 直接依赖 netpoll 的 develop 分支
2. 如 #52 所述，将 `eventLoop` 定义为 global var

**Comment by Hchenn** [comment]
ps: 另外 netpoll 有个隐式约定：OnRequest 需要处理完全部的数据，如果直接 `return nil` 的话，可能会出现无限循环的现象，还请注意。

**Comment by xj524598** [comment]
请问 这里的全部数据是指这一次io事件中涉及到的socket数据 还是指客户端完整的应用曾协议数据



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Hchen ***@***.***&gt;
发送时间: 2021年11月25日 17:43
收件人: cloudwego/netpoll ***@***.***&gt;
抄送: xj524598 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [cloudwego/netpoll] 运行普通的server端demo有问题 (Issue #80)

**Comment by Hchenn** [comment]
> 请问 这里的全部数据是指这一次io事件中涉及到的socket数据 还是指客户端完整的应用曾协议数据 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Hchen ***@***.***&gt; 发送时间: 2021年11月25日 17:43 收件人: cloudwego/netpoll ***@***.***&gt; 抄送: xj524598 ***@***.***&gt;, Author ***@***.***&gt; 主题: Re: [cloudwego/netpoll] 运行普通的server端demo有问题 (Issue #80)

是指 `connection.Reader().Len()` return 前要为 0，可以通过 `Reader` 提供的 API 获取或丢掉数据，具体可以参考 [这里](https://github.com/cloudwego/netpoll/blob/main/docs/guide/guide_cn.md#31-%E7%AE%80%E5%8D%95%E7%94%A8%E6%B3%95)

**Comment by xj524598** [comment]
![image](https://user-images.githubusercontent.com/26913796/143424980-b4935cdd-1f4a-4a83-b64a-0983f533fc29.png)
好像还是不行。。。 是我姿势不对吗 ?

**Comment by Hchenn** [comment]
18 行删掉冒号

**Comment by xj524598** [comment]
感谢，刚入门 没几天。
