### ISSUE TITLE
connection_reactor.go方法中onRequest方法是否可以仿照netty进行优化

### ISSUE THREAD

**Issue by xj524598** [cloudwego/netpoll#82]
如图，会有循环持续判断当前连接是否处理完毕，如果该链接接收一个很大的数据比如2个G，那么此次可能就会存在一直要读取完毕2G数据，才会处理下一个IO事件。进而造成其他请求被阻塞了
而在netty则会循环处理到一定次数（默认是16次）后，若发现还有数据未处理，则暂时设置一个flag，接着处理下一个io事件。未处理完毕的数据等待下一个轮询周期继续处理

![image](https://user-images.githubusercontent.com/26913796/143604253-b5c6eb6e-ac3f-4e7b-b1a5-c82abccf4c52.png)

**Comment by xj524598** [comment]
还有就是我如何通过电脑端飞书app 搜索到netpoll的飞书群

**Comment by Hchenn** [comment]
103行 定义了 `task` 是个任务，该任务在 [128行](https://github.com/cloudwego/netpoll/blob/main/connection_onevent.go#L128) 被扔到协程池进行处理，不会影响其他 I/O
